"""
Blender Scene: 41069048.blend
Objects: 71
Materials: 13
Generated by Export BPY Code addon v1.3.0
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'CYCLES'
bpy.context.scene.render.resolution_x = 640
bpy.context.scene.render.resolution_y = 640
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.cycles.samples = 24

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.6, 0.6, 0.6, 1.0)
    _bg.inputs['Strength'].default_value = 1.2

# ============================================================
# Materials
# ============================================================
mat_BlueTile = bpy.data.materials.new(name='BlueTile')
mat_BlueTile.use_nodes = True
_bsdf = mat_BlueTile.node_tree.nodes['Principled BSDF']
mat_BlueTile.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.55, 0.62, 0.7, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.0
mat_BlueTile.blend_method = 'HASHED'

mat_BrushHolder = bpy.data.materials.new(name='BrushHolder')
mat_BrushHolder.use_nodes = True
_bsdf = mat_BrushHolder.node_tree.nodes['Principled BSDF']
mat_BrushHolder.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.85, 0.85, 0.82, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0
mat_BrushHolder.blend_method = 'HASHED'

mat_Chrome = bpy.data.materials.new(name='Chrome')
mat_Chrome.use_nodes = True
_bsdf = mat_Chrome.node_tree.nodes['Principled BSDF']
mat_Chrome.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.8, 0.8, 0.82, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.1
_bsdf.inputs['Metallic'].default_value = 0.9
mat_Chrome.blend_method = 'HASHED'

mat_DarkPlastic = bpy.data.materials.new(name='DarkPlastic')
mat_DarkPlastic.use_nodes = True
_bsdf = mat_DarkPlastic.node_tree.nodes['Principled BSDF']
mat_DarkPlastic.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.08, 0.08, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0
mat_DarkPlastic.blend_method = 'HASHED'

mat_FloorTile = bpy.data.materials.new(name='FloorTile')
mat_FloorTile.use_nodes = True
_bsdf = mat_FloorTile.node_tree.nodes['Principled BSDF']
mat_FloorTile.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.9, 0.85, 0.75, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0
mat_FloorTile.blend_method = 'HASHED'

mat_Glass = bpy.data.materials.new(name='Glass')
mat_Glass.use_nodes = True
_bsdf = mat_Glass.node_tree.nodes['Principled BSDF']
mat_Glass.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.9, 0.95, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.15
mat_Glass.blend_method = 'BLEND'
mat_Glass.blend_method = 'BLEND'

mat_Soap = bpy.data.materials.new(name='Soap')
mat_Soap.use_nodes = True
_bsdf = mat_Soap.node_tree.nodes['Principled BSDF']
mat_Soap.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.85, 0.82, 0.55, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0
mat_Soap.blend_method = 'HASHED'

mat_Towel = bpy.data.materials.new(name='Towel')
mat_Towel.use_nodes = True
_bsdf = mat_Towel.node_tree.nodes['Principled BSDF']
mat_Towel.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.92, 0.9, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0
mat_Towel.blend_method = 'HASHED'

mat_WhiteCeramic = bpy.data.materials.new(name='WhiteCeramic')
mat_WhiteCeramic.use_nodes = True
_bsdf = mat_WhiteCeramic.node_tree.nodes['Principled BSDF']
mat_WhiteCeramic.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.95, 0.94, 0.92, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.0
mat_WhiteCeramic.blend_method = 'HASHED'

mat_WhitePlastic = bpy.data.materials.new(name='WhitePlastic')
mat_WhitePlastic.use_nodes = True
_bsdf = mat_WhitePlastic.node_tree.nodes['Principled BSDF']
mat_WhitePlastic.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0
mat_WhitePlastic.blend_method = 'HASHED'

mat_WhiteTile = bpy.data.materials.new(name='WhiteTile')
mat_WhiteTile.use_nodes = True
_bsdf = mat_WhiteTile.node_tree.nodes['Principled BSDF']
mat_WhiteTile.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.95, 0.93, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.2
_bsdf.inputs['Metallic'].default_value = 0.0
mat_WhiteTile.blend_method = 'HASHED'

mat_WoodDoor = bpy.data.materials.new(name='WoodDoor')
mat_WoodDoor.use_nodes = True
_bsdf = mat_WoodDoor.node_tree.nodes['Principled BSDF']
mat_WoodDoor.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.72, 0.52, 0.25, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0
mat_WoodDoor.blend_method = 'HASHED'

mat_WoodFloor = bpy.data.materials.new(name='WoodFloor')
mat_WoodFloor.use_nodes = True
_bsdf = mat_WoodFloor.node_tree.nodes['Principled BSDF']
mat_WoodFloor.diffuse_color = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Base Color'].default_value = (0.65, 0.45, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0
mat_WoodFloor.blend_method = 'HASHED'

# ============================================================
# Objects
# ============================================================
# WARNING: Complex mesh 'Bathtub' (verts=100, faces=70)
# Approximated as cube — replace with primitives or supported procedural modifiers
bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.750839, 0.650532, 0.596766))
obj = bpy.context.active_object
obj.name = 'Bathtub'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.525848, 1.63, 0.602742)
obj.data.name = 'Cylinder.036'
obj.data.materials.append(bpy.data.materials['Chrome'])
obj.data.materials.append(bpy.data.materials['WhiteCeramic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.55361, -1.22582, 1.06))
obj = bpy.context.active_object
obj.name = 'Bottle_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0464, 0.0464, 0.1)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Soap'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.627615, -1.193648, 1.06))
obj = bpy.context.active_object
obj.name = 'Bottle_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0464, 0.0464, 0.1)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Soap'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.696, -1.217261, 1.05))
obj = bpy.context.active_object
obj.name = 'Bottle_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0464, 0.0464, 0.08)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Soap'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.131919, 0.356048, 1.45))
obj = bpy.context.active_object
obj.name = 'CautionSign'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0116, 0.29, 0.08)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['WhitePlastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.0696, depth=0.03, location=(-0.232, 0.348, 2.39))
obj = bpy.context.active_object
obj.name = 'CeilingLight_Housing'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.029'
obj.data.materials.append(bpy.data.materials['WhitePlastic'])

bpy.ops.object.light_add(type='POINT', location=(-0.232, 0.348, 2.3))
obj = bpy.context.active_object
obj.name = 'CeilingLight_Source'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 200.0
obj.data.color = (1.0, 0.95, 0.85)
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.01392, depth=0.1, location=(1.588802, -0.42464, 1.13022))
obj = bpy.context.active_object
obj.name = 'Door_Handle'
obj.rotation_euler = (-1.706236, 1.864339, -3.852404)
obj.data.name = 'Cylinder.038'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -1.019502, 0.3))
obj = bpy.context.active_object
obj.name = 'Door_Hinge_0.3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0348, 0.0464, 0.08)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['DarkPlastic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -1.026909, 1.7))
obj = bpy.context.active_object
obj.name = 'Door_Hinge_1.7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0348, 0.0464, 0.08)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['DarkPlastic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.485918, -0.684734, 1.025))
obj = bpy.context.active_object
obj.name = 'Door_Panel'
obj.rotation_euler = (0.0, -0.0, -0.573417)
obj.scale = (0.058, 0.87, 2.05)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['WoodDoor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -1.0498, 1.025))
obj = bpy.context.active_object
obj.name = 'DoorFrame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.116, 0.0696, 2.05)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -0.1102, 1.025))
obj = bpy.context.active_object
obj.name = 'DoorFrame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.116, 0.0696, 2.05)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -0.58, 2.09))
obj = bpy.context.active_object
obj.name = 'DoorFrame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.116, 0.986, 0.06)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.58, -1.3108, 1.5))
obj = bpy.context.active_object
obj.name = 'ElectricalOutlet'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 0.0116, 0.05)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['WhitePlastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.0812, depth=0.01, location=(0.58, 0.928, 2.37))
obj = bpy.context.active_object
obj.name = 'ExhaustFan_Grill'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.031'
obj.data.materials.append(bpy.data.materials['WhitePlastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.116, depth=0.04, location=(0.58, 0.928, 2.39))
obj = bpy.context.active_object
obj.name = 'ExhaustFan_Housing'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.030'
obj.data.materials.append(bpy.data.materials['DarkPlastic'])

bpy.ops.object.light_add(type='AREA', location=(2.173751, -1.134496, 2.300115))
obj = bpy.context.active_object
obj.name = 'FillLight_Source'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 50.0
obj.data.color = (1.0, 0.97, 0.9)
obj.data.size = 1.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.02))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.552, 2.784, 0.04)
obj.data.name = 'Cube.001'
obj.data.materials.append(bpy.data.materials['FloorTile'])

bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=0.029, depth=0.015, location=(0.403394, 1.090356, 0.57))
obj = bpy.context.active_object
obj.name = 'Flush_Button'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.797521, -1.191167, 1.0))
obj = bpy.context.active_object
obj.name = 'Glass_Shelf'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.58, 0.116, 0.01)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.13306, 0.037039, 1.15))
obj = bpy.context.active_object
obj.name = 'LightSwitch'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0116, 0.0928, 0.08)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['WhitePlastic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.110387, -1.264772, 1.480949))
obj = bpy.context.active_object
obj.name = 'Mirror'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.985729, 0.0232, 0.6)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.445317, -0.121713, -0.02))
obj = bpy.context.active_object
obj.name = 'OutsideFloor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.473654, 2.462182, 0.04)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['WoodFloor'])

bpy.ops.object.camera_add(location=(-1.17392, -1.28064, 2.208))
obj = bpy.context.active_object
obj.name = 'RefineCam'
obj.rotation_euler = (0.936029, -0.0, -0.741947)
obj.data.lens = 16.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.object.light_add(type='SUN', location=(0.0, 0.0, 4.4))
obj = bpy.context.active_object
obj.name = 'RefineSun'
obj.rotation_euler = (0.5, 0.2, 0.3)
obj.data.energy = 4.0

bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=0.0696, depth=0.3, location=(0.942596, -1.218372, 1.06))
obj = bpy.context.active_object
obj.name = 'Rolled_Towel'
obj.rotation_euler = (0.0, 1.5708, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['Towel'])

bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=0.0232, depth=0.1, location=(-0.7322, 1.209102, 1.481034))
obj = bpy.context.active_object
obj.name = 'Shower_Hose_Mount'
obj.rotation_euler = (1.51632, 1.570793, 0.0)
obj.data.name = 'Cylinder.035'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.0696, depth=0.03, location=(-0.7322, 1.209102, 1.681034))
obj = bpy.context.active_object
obj.name = 'Shower_Valve'
obj.rotation_euler = (1.51632, 1.570793, 0.0)
obj.data.name = 'Cylinder.034'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.430148, 1.258, 1.25))
obj = bpy.context.active_object
obj.name = 'ShowerScreen_Frame_Side'
obj.rotation_euler = (0.0, -0.0, -3.138867)
obj.scale = (0.0348, 0.0232, 1.4)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.428726, 0.736002, 1.95))
obj = bpy.context.active_object
obj.name = 'ShowerScreen_Frame_Top'
obj.rotation_euler = (0.0, -0.0, -3.138867)
obj.scale = (0.0348, 1.0672, 0.02)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.428726, 0.736002, 1.25))
obj = bpy.context.active_object
obj.name = 'ShowerScreen_Glass'
obj.rotation_euler = (0.0, -0.0, -3.138867)
obj.scale = (0.0232, 1.044, 1.4)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.101267, -1.13699, 0.84))
obj = bpy.context.active_object
obj.name = 'Sink_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6032, 0.0696, 0.08)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['WhiteCeramic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.29, depth=0.12, location=(0.101267, -1.043818, 0.82))
obj = bpy.context.active_object
obj.name = 'Sink_Basin'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.0, 0.8, 1.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['WhiteCeramic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=0.0232, depth=0.15, location=(0.101267, -1.125018, 0.94))
obj = bpy.context.active_object
obj.name = 'Sink_Faucet_Spout'
obj.rotation_euler = (0.8, 0.0, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.02088, depth=0.04, location=(0.008467, -1.125018, 0.92))
obj = bpy.context.active_object
obj.name = 'Sink_Handle_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.02088, depth=0.04, location=(0.194067, -1.125018, 0.92))
obj = bpy.context.active_object
obj.name = 'Sink_Handle_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.116, depth=0.75, location=(0.101267, -1.101818, 0.375))
obj = bpy.context.active_object
obj.name = 'Sink_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['WhiteCeramic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.284325, -1.112019, 0.9))
obj = bpy.context.active_object
obj.name = 'Soap'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0696, 0.0464, 0.025)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Soap'])

# WARNING: Complex mesh 'Toilet' (verts=2116, faces=1734)
# Approximated as cube — replace with primitives or supported procedural modifiers
bpy.ops.mesh.primitive_cube_add(size=1, location=(0.171942, 0.798064, 0.140756))
obj = bpy.context.active_object
obj.name = 'Toilet'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.461539, 0.75, 0.562003)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['WhiteCeramic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.25, location=(0.763628, 0.83432, 0.38))
obj = bpy.context.active_object
obj.name = 'ToiletBrush_Handle'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=16, radius=0.058, depth=0.3, location=(0.763628, 0.83432, 0.15))
obj = bpy.context.active_object
obj.name = 'ToiletBrush_Holder'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['BrushHolder'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.140404, 0.356048, 1.0))
obj = bpy.context.active_object
obj.name = 'Towel_OnRail'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 0.291262, 0.45)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Towel'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.5))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_0'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.585))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_1'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.67))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_2'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.755))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_3'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.019'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.84))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_4'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.020'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 0.925))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_5'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.021'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 1.01))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_6'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.022'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 1.095))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_7'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.023'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 1.18))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_8'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.024'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=8, radius=0.00928, depth=0.3, location=(1.143519, 0.356048, 1.265))
obj = bpy.context.active_object
obj.name = 'TowelRail_Rung_9'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Cylinder.025'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.01392, depth=0.8, location=(1.143519, 0.182048, 0.9))
obj = bpy.context.active_object
obj.name = 'TowelRail_Vert_-0.15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.01392, depth=0.8, location=(1.143519, 0.530048, 0.9))
obj = bpy.context.active_object
obj.name = 'TowelRail_Vert_0.15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.067822, 1.298017, 0.595274))
obj = bpy.context.active_object
obj.name = 'TP_Holder_Mount'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0464, 0.0464, 0.04)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_torus_add(major_radius=0.07088, minor_radius=0.008, location=(0.067822, 1.233168, 0.595274))
obj = bpy.context.active_object
obj.name = 'TP_Holder_Ring'
obj.rotation_euler = (1.5708, 0.0, 0.0)
obj.data.name = 'Torus'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.0928, depth=0.22, location=(1.020081, 0.759125, 0.11))
obj = bpy.context.active_object
obj.name = 'TrashCan_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.026'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=24, radius=0.0986, depth=0.02, location=(1.020081, 0.759125, 0.23))
obj = bpy.context.active_object
obj.name = 'TrashCan_Lid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.027'
obj.data.materials.append(bpy.data.materials['Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.020081, 0.666325, 0.02))
obj = bpy.context.active_object
obj.name = 'TrashCan_Pedal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0464, 0.0464, 0.015)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['DarkPlastic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 1.3456, 0.5))
obj = bpy.context.active_object
obj.name = 'Wall_Back_Lower'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.552, 0.0928, 1.0)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 1.3456, 1.7))
obj = bpy.context.active_object
obj.name = 'Wall_Back_Upper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.552, 0.0928, 1.4)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['BlueTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.240269, -1.3456, 0.5))
obj = bpy.context.active_object
obj.name = 'Wall_Front_Lower'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (4.872553, 0.0928, 1.0)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.240269, -1.3456, 1.7))
obj = bpy.context.active_object
obj.name = 'Wall_Front_Upper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (4.872553, 0.0928, 1.4)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['BlueTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.2296, 0.0, 0.5))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Lower'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 2.784, 1.0)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.2296, 0.0, 1.7))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Upper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 2.784, 1.4)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['BlueTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -0.58, 2.225))
obj = bpy.context.active_object
obj.name = 'Wall_Right_AboveDoor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 0.87, 0.35)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['BlueTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -1.2035, 0.5))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Seg1_Lower'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 0.377, 1.0)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, -1.2035, 1.7))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Seg1_Upper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 0.377, 1.4)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['BlueTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, 0.6235, 0.5))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Seg2_Lower'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 1.537, 1.0)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['WhiteTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2296, 0.6235, 1.7))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Seg2_Upper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.0928, 1.537, 1.4)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['BlueTile'])

