"""
Blender Scene: 42897692.blend
Objects: 121
Materials: 22
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.95, 0.9, 0.82, 1.0)
    _bg.inputs['Strength'].default_value = 0.3

# ============================================================
# Materials
# ============================================================
mat_Changing_Pad_Dark = bpy.data.materials.new(name='Changing_Pad_Dark')
mat_Changing_Pad_Dark.use_nodes = True
_bsdf = mat_Changing_Pad_Dark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.3, 0.32, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Curtain_Blue = bpy.data.materials.new(name='Curtain_Blue')
mat_Curtain_Blue.use_nodes = True
_bsdf = mat_Curtain_Blue.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.65, 0.75, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Door_White = bpy.data.materials.new(name='Door_White')
mat_Door_White.use_nodes = True
_bsdf = mat_Door_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.9, 0.87, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Floor_Wood = bpy.data.materials.new(name='Floor_Wood')
mat_Floor_Wood.use_nodes = True
_bsdf = mat_Floor_Wood.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.53, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Gold_Knob = bpy.data.materials.new(name='Gold_Knob')
mat_Gold_Knob.use_nodes = True
_bsdf = mat_Gold_Knob.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.85, 0.7, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mirror_Silver = bpy.data.materials.new(name='Mirror_Silver')
mat_Mirror_Silver.use_nodes = True
_bsdf = mat_Mirror_Silver.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.85, 0.85, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Pet_Bed_Gray = bpy.data.materials.new(name='Pet_Bed_Gray')
mat_Pet_Bed_Gray.use_nodes = True
_bsdf = mat_Pet_Bed_Gray.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.55, 0.57, 0.6, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Picture_Frame = bpy.data.materials.new(name='Picture_Frame')
mat_Picture_Frame.use_nodes = True
_bsdf = mat_Picture_Frame.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.4, 0.35, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Poster_Color = bpy.data.materials.new(name='Poster_Color')
mat_Poster_Color.use_nodes = True
_bsdf = mat_Poster_Color.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.75, 0.55, 0.35, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Radiator_White = bpy.data.materials.new(name='Radiator_White')
mat_Radiator_White.use_nodes = True
_bsdf = mat_Radiator_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Rug_Blue = bpy.data.materials.new(name='Rug_Blue')
mat_Rug_Blue.use_nodes = True
_bsdf = mat_Rug_Blue.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.55, 0.6, 0.7, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Rug_Pattern = bpy.data.materials.new(name='Rug_Pattern')
mat_Rug_Pattern.use_nodes = True
_bsdf = mat_Rug_Pattern.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.62, 0.55, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Rug_Red = bpy.data.materials.new(name='Rug_Red')
mat_Rug_Red.use_nodes = True
_bsdf = mat_Rug_Red.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.15, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Storage_LightBlue = bpy.data.materials.new(name='Storage_LightBlue')
mat_Storage_LightBlue.use_nodes = True
_bsdf = mat_Storage_LightBlue.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.78, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wall_Cream = bpy.data.materials.new(name='Wall_Cream')
mat_Wall_Cream.use_nodes = True
_bsdf = mat_Wall_Cream.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.93, 0.89, 0.82, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_White_Bedding = bpy.data.materials.new(name='White_Bedding')
mat_White_Bedding.use_nodes = True
_bsdf = mat_White_Bedding.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.97, 0.96, 0.94, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_White_Furniture = bpy.data.materials.new(name='White_Furniture')
mat_White_Furniture.use_nodes = True
_bsdf = mat_White_Furniture.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.93, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wicker_Brown = bpy.data.materials.new(name='Wicker_Brown')
mat_Wicker_Brown.use_nodes = True
_bsdf = mat_Wicker_Brown.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.5, 0.32, 0.15, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Window_Glass = bpy.data.materials.new(name='Window_Glass')
mat_Window_Glass.use_nodes = True
_bsdf = mat_Window_Glass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.7, 0.8, 0.3)
_bsdf.inputs['Roughness'].default_value = 0.1
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.3
mat_Window_Glass.blend_method = 'BLEND'

mat_Wood_Dark_Frame = bpy.data.materials.new(name='Wood_Dark_Frame')
mat_Wood_Dark_Frame.use_nodes = True
_bsdf = mat_Wood_Dark_Frame.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.45, 0.25, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wood_Light_Oak = bpy.data.materials.new(name='Wood_Light_Oak')
mat_Wood_Light_Oak.use_nodes = True
_bsdf = mat_Wood_Light_Oak.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.48, 0.28, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wood_Medium = bpy.data.materials.new(name='Wood_Medium')
mat_Wood_Medium.use_nodes = True
_bsdf = mat_Wood_Medium.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.55, 0.35, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.mesh.primitive_cube_add(size=1, location=(2.8, 0.9, 0.175))
obj = bpy.context.active_object
obj.name = 'Bed_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.6, 2.0, 0.35)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.8, -0.06, 0.85))
obj = bpy.context.active_object
obj.name = 'Bed_Headboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.6, 0.08, 0.5)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.8, 0.9, 0.475))
obj = bpy.context.active_object
obj.name = 'Bed_Mattress'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.55, 1.95, 0.25)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.45, 0.15, 0.68))
obj = bpy.context.active_object
obj.name = 'Bed_Pillow_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.55, 0.35, 0.12)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.15, 0.15, 0.68))
obj = bpy.context.active_object
obj.name = 'Bed_Pillow_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.55, 0.35, 0.12)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.object.camera_add(location=(2.25, -1.5, 2.0))
obj = bpy.context.active_object
obj.name = 'Camera'
obj.rotation_euler = (1.22173, 0.0, 0.0)
obj.data.lens = 28.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.object.light_add(type='AREA', location=(2.25, 2.0, 2.65))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 150.0
obj.data.color = (1.0, 0.95, 0.85)
obj.data.size = 1.5

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.6, 0.35))
obj = bpy.context.active_object
obj.name = 'ChangingTable_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.65, 0.45, 0.7)
obj.data.name = 'Cube.067'
obj.data.materials.append(bpy.data.materials['Wood_Light_Oak'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.6, 0.765))
obj = bpy.context.active_object
obj.name = 'ChangingTable_Liner'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.55, 0.35, 0.05)
obj.data.name = 'Cube.071'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.6, 0.76))
obj = bpy.context.active_object
obj.name = 'ChangingTable_Pad'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6, 0.42, 0.08)
obj.data.name = 'Cube.068'
obj.data.materials.append(bpy.data.materials['Changing_Pad_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.435, 0.8))
obj = bpy.context.active_object
obj.name = 'ChangingTable_PadEdge_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6, 0.04, 0.12)
obj.data.name = 'Cube.069'
obj.data.materials.append(bpy.data.materials['Changing_Pad_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.765, 0.8))
obj = bpy.context.active_object
obj.name = 'ChangingTable_PadEdge_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6, 0.04, 0.12)
obj.data.name = 'Cube.070'
obj.data.materials.append(bpy.data.materials['Changing_Pad_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 0.65, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.75, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 0.772222, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 0.894444, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.016667, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.138889, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.261111, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.383333, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.505556, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.627778, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Left_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 0.65, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.75, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 0.772222, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 0.894444, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.016667, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.138889, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.261111, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.383333, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.505556, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.627778, 0.625))
obj = bpy.context.active_object
obj.name = 'Crib_Bar_Right_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.51)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 1.2, 0.35))
obj = bpy.context.active_object
obj.name = 'Crib_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.7, 1.3, 0.05)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 1.2, 0.425))
obj = bpy.context.active_object
obj.name = 'Crib_Mattress'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.66, 1.26, 0.1)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 1.83, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Panel_Foot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.66, 0.03, 0.86)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 0.57, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Panel_Head'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.66, 0.03, 0.86)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 0.57, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Post_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.9)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 0.57, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Post_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.9)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.83, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Post_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.9)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.83, 0.45))
obj = bpy.context.active_object
obj.name = 'Crib_Post_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.9)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 0.57, 0.88))
obj = bpy.context.active_object
obj.name = 'Crib_Rail_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.7, 0.04, 0.03)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 1.83, 0.88))
obj = bpy.context.active_object
obj.name = 'Crib_Rail_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.7, 0.04, 0.03)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.42, 1.2, 0.88))
obj = bpy.context.active_object
obj.name = 'Crib_Rail_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 1.3, 0.03)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.08, 1.2, 0.88))
obj = bpy.context.active_object
obj.name = 'Crib_Rail_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 1.3, 0.03)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.62, 1.65))
obj = bpy.context.active_object
obj.name = 'Crucifix_Horizontal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.1, 0.02)
obj.data.name = 'Cube.109'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 3.62, 1.6))
obj = bpy.context.active_object
obj.name = 'Crucifix_Vertical'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.02, 0.15)
obj.data.name = 'Cube.108'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.545, 4.0, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.18, 2.1)
obj.data.name = 'Cube.088'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.455, 4.0, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.18, 2.1)
obj.data.name = 'Cube.089'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.0, 4.0, 2.13))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.97, 0.18, 0.06)
obj.data.name = 'Cube.090'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.0, 4.02, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Panel'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.83, 0.04, 2.06)
obj.data.name = 'Cube.091'
obj.data.materials.append(bpy.data.materials['Door_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.1, 2.5, 0.425))
obj = bpy.context.active_object
obj.name = 'Dresser_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6, 0.9, 0.85)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.795, 2.5, 0.19375))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.84, 0.1675)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.795, 2.5, 0.38125))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.84, 0.1675)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.795, 2.5, 0.56875))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.84, 0.1675)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.795, 2.5, 0.75625))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.84, 0.1675)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.015, location=(3.78, 2.5, 0.19375))
obj = bpy.context.active_object
obj.name = 'Dresser_Knob_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere'
obj.data.materials.append(bpy.data.materials['Gold_Knob'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.015, location=(3.78, 2.5, 0.38125))
obj = bpy.context.active_object
obj.name = 'Dresser_Knob_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.001'
obj.data.materials.append(bpy.data.materials['Gold_Knob'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.015, location=(3.78, 2.5, 0.56875))
obj = bpy.context.active_object
obj.name = 'Dresser_Knob_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.002'
obj.data.materials.append(bpy.data.materials['Gold_Knob'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.015, location=(3.78, 2.5, 0.75625))
obj = bpy.context.active_object
obj.name = 'Dresser_Knob_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.003'
obj.data.materials.append(bpy.data.materials['Gold_Knob'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.925, 2.5, 1.2))
obj = bpy.context.active_object
obj.name = 'Dresser_Mirror'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.005, 0.45, 0.45)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['Mirror_Silver'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.95, 2.5, 1.2))
obj = bpy.context.active_object
obj.name = 'Dresser_Mirror_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.5, 0.5)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.1, 2.5, 0.865))
obj = bpy.context.active_object
obj.name = 'Dresser_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.63, 0.93, 0.03)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['White_Furniture'])

bpy.ops.object.light_add(type='POINT', location=(2.25, 2.0, 2.0))
obj = bpy.context.active_object
obj.name = 'Fill_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 50.0
obj.data.color = (1.0, 0.93, 0.82)
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.25, 2.0, -0.05))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (4.5, 4.0, 0.1)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Floor_Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 0.01, 1.9))
obj = bpy.context.active_object
obj.name = 'Painting_Canvas'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.01, 0.34)
obj.data.name = 'Cube.107'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 0.02, 1.9))
obj = bpy.context.active_object
obj.name = 'Painting_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.5, 0.03, 0.4)
obj.data.name = 'Cube.106'
obj.data.materials.append(bpy.data.materials['Picture_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.5, 3.0, 0.06))
obj = bpy.context.active_object
obj.name = 'PetBed_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.5, 0.4, 0.12)
obj.data.name = 'Cube.083'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.5, 3.17, 0.16))
obj = bpy.context.active_object
obj.name = 'PetBed_Edge_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.5, 0.06, 0.08)
obj.data.name = 'Cube.085'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.5, 2.83, 0.16))
obj = bpy.context.active_object
obj.name = 'PetBed_Edge_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.5, 0.06, 0.08)
obj.data.name = 'Cube.084'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.28, 3.0, 0.16))
obj = bpy.context.active_object
obj.name = 'PetBed_Edge_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.4, 0.08)
obj.data.name = 'Cube.086'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.72, 3.0, 0.16))
obj = bpy.context.active_object
obj.name = 'PetBed_Edge_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.4, 0.08)
obj.data.name = 'Cube.087'
obj.data.materials.append(bpy.data.materials['Pet_Bed_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, 0.3, 0.005))
obj = bpy.context.active_object
obj.name = 'Poster_Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.4, 0.55, 0.005)
obj.data.name = 'Cube.104'
obj.data.materials.append(bpy.data.materials['White_Bedding'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, 0.3, 0.011))
obj = bpy.context.active_object
obj.name = 'Poster_Image'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.3, 0.42, 0.003)
obj.data.name = 'Cube.105'
obj.data.materials.append(bpy.data.materials['Poster_Color'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.12, 1.2, 0.375))
obj = bpy.context.active_object
obj.name = 'Radiator_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 1.0, 0.55)
obj.data.name = 'Cube.072'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.18125))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.073'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.24375))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.074'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.30625))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.075'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.36875))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.076'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.43125))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.077'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.49375))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.078'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.55625))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.079'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.075, 1.2, 0.61875))
obj = bpy.context.active_object
obj.name = 'Radiator_Rib_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.01, 0.98, 0.025)
obj.data.name = 'Cube.080'
obj.data.materials.append(bpy.data.materials['Radiator_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.75, 1.2, 0.005))
obj = bpy.context.active_object
obj.name = 'Rug_Pattern'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 1.6, 0.01)
obj.data.name = 'Cube.110'
obj.data.materials.append(bpy.data.materials['Rug_Pattern'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.9, 0.005))
obj = bpy.context.active_object
obj.name = 'Rug_Red'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 0.7, 0.01)
obj.data.name = 'Cube.112'
obj.data.materials.append(bpy.data.materials['Rug_Red'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.2, 3.2, 0.005))
obj = bpy.context.active_object
obj.name = 'Rug_Small_Blue'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.6, 0.5, 0.01)
obj.data.name = 'Cube.111'
obj.data.materials.append(bpy.data.materials['Rug_Blue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.3, 2.5, 0.25))
obj = bpy.context.active_object
obj.name = 'StorageBox_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.45, 0.35, 0.5)
obj.data.name = 'Cube.081'
obj.data.materials.append(bpy.data.materials['Storage_LightBlue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.3, 2.5, 0.53))
obj = bpy.context.active_object
obj.name = 'StorageBox_Cover'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.5, 0.4, 0.04)
obj.data.name = 'Cube.082'
obj.data.materials.append(bpy.data.materials['Storage_LightBlue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.6, 0.5))
obj = bpy.context.active_object
obj.name = 'TallChest_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.85, 0.5, 1.0)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['Wood_Light_Oak'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.156667))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.31))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.463333))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.616667))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.77))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.345, 0.923333))
obj = bpy.context.active_object
obj.name = 'TallChest_Drawer_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.81, 0.01, 0.138333)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['Wood_Medium'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.6, 1.015))
obj = bpy.context.active_object
obj.name = 'TallChest_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.87, 0.52, 0.03)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['Wood_Light_Oak'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.25, -0.075, 1.35))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (4.8, 0.15, 2.7)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Wall_Cream'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.25, 4.075, 1.35))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (4.8, 0.15, 2.7)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Wall_Cream'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.075, 2.0, 1.35))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 4.0, 2.7)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Wall_Cream'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.575, 2.0, 1.35))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 4.0, 2.7)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['Wall_Cream'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, 3.75, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.6, 0.55, 2.2)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, 3.455, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Divider'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.04, 2.15)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.4, 3.465, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Door_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.74, 0.03, 2.1)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['Door_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.2, 3.465, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Door_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.74, 0.03, 2.1)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['Door_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.02, 3.455, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_SideTrim_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.04, 2.15)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.58, 3.455, 1.1))
obj = bpy.context.active_object
obj.name = 'Wardrobe_SideTrim_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.04, 2.15)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, 3.455, 2.18))
obj = bpy.context.active_object
obj.name = 'Wardrobe_TopTrim'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.6, 0.04, 0.03)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.25, depth=0.65, location=(3.0, 3.6, 0.325))
obj = bpy.context.active_object
obj.name = 'WickerBasket_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Wicker_Brown'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.27, depth=0.04, location=(3.0, 3.6, 0.67))
obj = bpy.context.active_object
obj.name = 'WickerBasket_Lid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Wicker_Brown'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.0, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_CrossBar'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.9, 0.03)
obj.data.name = 'Cube.102'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.45, 1.0, 2.48))
obj = bpy.context.active_object
obj.name = 'Window_Curtain'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 1.05, 0.12)
obj.data.name = 'Cube.103'
obj.data.materials.append(bpy.data.materials['Curtain_Blue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.0, 1.17))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Bottom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 1.0, 0.05)
obj.data.name = 'Cube.095'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.0, 1.17))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Bottom.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 1.0, 0.05)
obj.data.name = 'Cube.100'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 0.52, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.05, 1.26)
obj.data.name = 'Cube.092'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 0.52, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Left.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.05, 1.26)
obj.data.name = 'Cube.097'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.48, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.05, 1.26)
obj.data.name = 'Cube.093'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.48, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Right.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.05, 1.26)
obj.data.name = 'Cube.098'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.0, 2.43))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 1.0, 0.05)
obj.data.name = 'Cube.094'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.5, 1.0, 2.43))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Top.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 1.0, 0.05)
obj.data.name = 'Cube.099'
obj.data.materials.append(bpy.data.materials['Wood_Dark_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.52, 1.0, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.86, 1.16)
obj.data.name = 'Cube.096'
obj.data.materials.append(bpy.data.materials['Window_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.52, 1.0, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Glass.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.86, 1.16)
obj.data.name = 'Cube.101'
obj.data.materials.append(bpy.data.materials['Window_Glass'])

bpy.ops.object.light_add(type='AREA', location=(4.6, 1.0, 1.8))
obj = bpy.context.active_object
obj.name = 'Window_Light'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.energy = 80.0
obj.data.color = (0.9, 0.92, 1.0)
obj.data.size = 0.8

