"""
Blender Scene: 42899720.blend
Objects: 67
Materials: 17
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.95, 0.93, 0.9, 1.0)
    _bg.inputs['Strength'].default_value = 0.3

# ============================================================
# Materials
# ============================================================
mat_Mat_Bed_Dark = bpy.data.materials.new(name='Mat_Bed_Dark')
mat_Mat_Bed_Dark.use_nodes = True
_bsdf = mat_Mat_Bed_Dark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.25, 0.22, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Bed_White = bpy.data.materials.new(name='Mat_Bed_White')
mat_Mat_Bed_White.use_nodes = True
_bsdf = mat_Mat_Bed_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.9, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Carpet = bpy.data.materials.new(name='Mat_Carpet')
mat_Mat_Carpet.use_nodes = True
_bsdf = mat_Mat_Carpet.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.48, 0.48, 0.47, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Chrome = bpy.data.materials.new(name='Mat_Chrome')
mat_Mat_Chrome.use_nodes = True
_bsdf = mat_Mat_Chrome.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.8, 0.8, 0.8, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.1
_bsdf.inputs['Metallic'].default_value = 1.0

mat_Mat_Door = bpy.data.materials.new(name='Mat_Door')
mat_Mat_Door.use_nodes = True
_bsdf = mat_Mat_Door.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.93, 0.93, 0.93, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Floor_Beige = bpy.data.materials.new(name='Mat_Floor_Beige')
mat_Mat_Floor_Beige.use_nodes = True
_bsdf = mat_Mat_Floor_Beige.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.76, 0.67, 0.52, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Glass = bpy.data.materials.new(name='Mat_Glass')
mat_Mat_Glass.use_nodes = True
_bsdf = mat_Mat_Glass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.85, 0.88, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.2
mat_Mat_Glass.blend_method = 'BLEND'

mat_Mat_Light_Emit = bpy.data.materials.new(name='Mat_Light_Emit')
mat_Mat_Light_Emit.use_nodes = True
_bsdf = mat_Mat_Light_Emit.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (1.0, 0.95, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Emission Strength'].default_value = 5.0
_bsdf.inputs['Emission Color'].default_value = (1.0, 0.95, 0.85, 1.0)

mat_Mat_Mirror = bpy.data.materials.new(name='Mat_Mirror')
mat_Mat_Mirror.use_nodes = True
_bsdf = mat_Mat_Mirror.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.9, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.0
_bsdf.inputs['Metallic'].default_value = 1.0

mat_Mat_Porcelain = bpy.data.materials.new(name='Mat_Porcelain')
mat_Mat_Porcelain.use_nodes = True
_bsdf = mat_Mat_Porcelain.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Poster = bpy.data.materials.new(name='Mat_Poster')
mat_Mat_Poster.use_nodes = True
_bsdf = mat_Mat_Poster.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.9, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Shower_Base = bpy.data.materials.new(name='Mat_Shower_Base')
mat_Mat_Shower_Base.use_nodes = True
_bsdf = mat_Mat_Shower_Base.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.92, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Tile_Gray = bpy.data.materials.new(name='Mat_Tile_Gray')
mat_Mat_Tile_Gray.use_nodes = True
_bsdf = mat_Mat_Tile_Gray.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.54, 0.56, 0.52, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Toilet_Paper = bpy.data.materials.new(name='Mat_Toilet_Paper')
mat_Mat_Toilet_Paper.use_nodes = True
_bsdf = mat_Mat_Toilet_Paper.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.94, 0.92, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Vent = bpy.data.materials.new(name='Mat_Vent')
mat_Mat_Vent.use_nodes = True
_bsdf = mat_Mat_Vent.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.3, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Wall_White = bpy.data.materials.new(name='Mat_Wall_White')
mat_Mat_Wall_White.use_nodes = True
_bsdf = mat_Mat_Wall_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.9, 0.87, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Window_Glass = bpy.data.materials.new(name='Mat_Window_Glass')
mat_Mat_Window_Glass.use_nodes = True
_bsdf = mat_Mat_Window_Glass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.8, 0.85, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.0
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.3
mat_Mat_Window_Glass.blend_method = 'BLEND'

# ============================================================
# Objects
# ============================================================
bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 1.3, 0.55))
obj = bpy.context.active_object
obj.name = 'Bed_Covers'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 1.4, 0.1)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['Mat_Bed_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 1.5, 0.2))
obj = bpy.context.active_object
obj.name = 'Bed_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 2.0, 0.4)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['Mat_Bed_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 1.5, 0.45))
obj = bpy.context.active_object
obj.name = 'Bed_Mattress'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.3, 1.9, 0.1)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['Mat_Bed_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, 2.25, 0.53))
obj = bpy.context.active_object
obj.name = 'Bed_Pillow'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.55, 0.35, 0.08)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['Mat_Bed_White'])

bpy.ops.object.light_add(type='POINT', location=(-1.5, 1.5, 2.4))
obj = bpy.context.active_object
obj.name = 'Bedroom_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 30.0
obj.data.color = (1.0, 0.95, 0.85)
obj.data.shadow_soft_size = 0.0

bpy.ops.object.camera_add(location=(0.9, 0.3, 1.9))
obj = bpy.context.active_object
obj.name = 'Camera'
obj.rotation_euler = (0.785398, 0.0, 0.139626)
obj.data.lens = 18.0
obj.data.clip_start = 0.01
obj.data.clip_end = 1000.0

bpy.ops.object.light_add(type='POINT', location=(1.5, 0.5, 2.45))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 80.0
obj.data.color = (1.0, 0.95, 0.85)
obj.data.shadow_soft_size = 0.1

bpy.ops.object.light_add(type='POINT', location=(0.6, 1.2, 2.45))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 80.0
obj.data.color = (1.0, 0.95, 0.85)
obj.data.shadow_soft_size = 0.1

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 0.28, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.14, 0.04, 2.1)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 1.12, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.14, 0.04, 2.1)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 0.7, 2.125))
obj = bpy.context.active_object
obj.name = 'Door_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.14, 0.88, 0.05)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.012, depth=0.08, location=(0.03, -0.25, 0.0))
obj = bpy.context.active_object
obj.name = 'Door_Handle'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.02, 1.1, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Panel'
obj.rotation_euler = (0.0, 0.0, 0.785398)
obj.scale = (0.04, 0.8, 2.1)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['Mat_Door'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 0.9, -0.025))
obj = bpy.context.active_object
obj.name = 'Floor_Bathroom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.0, 1.8, 0.05)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Mat_Floor_Beige'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.5, 1.5, -0.025))
obj = bpy.context.active_object
obj.name = 'Floor_Bedroom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 3.0, 0.05)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Mat_Carpet'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.02, location=(1.5, 0.5, 2.49))
obj = bpy.context.active_object
obj.name = 'Light_Fixture_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['Mat_Light_Emit'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.02, location=(0.6, 1.2, 2.49))
obj = bpy.context.active_object
obj.name = 'Light_Fixture_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['Mat_Light_Emit'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.9, 1.79, 1.35))
obj = bpy.context.active_object
obj.name = 'Mirror'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.35, 0.02, 0.45)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['Mat_Mirror'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.8, 0.6, 0.005))
obj = bpy.context.active_object
obj.name = 'Poster'
obj.rotation_euler = (0.0, 0.0, -0.261799)
obj.scale = (0.25, 0.35, 0.002)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Mat_Poster'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, 0.5, 0.04))
obj = bpy.context.active_object
obj.name = 'Shower_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.9, 0.08)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Mat_Shower_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, 0.06, 2.08))
obj = bpy.context.active_object
obj.name = 'Shower_Frame_Top_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.03, 0.03)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.11, 0.5, 2.08))
obj = bpy.context.active_object
obj.name = 'Shower_Frame_Top_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.9, 0.03)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.11, 0.95, 1.08))
obj = bpy.context.active_object
obj.name = 'Shower_Frame_Vert_BL'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.03, 2.0)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.11, 0.06, 1.08))
obj = bpy.context.active_object
obj.name = 'Shower_Frame_Vert_Corner'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.03, 2.0)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, 0.06, 1.08))
obj = bpy.context.active_object
obj.name = 'Shower_Frame_Vert_FR'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.03, 2.0)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, 0.06, 1.08))
obj = bpy.context.active_object
obj.name = 'Shower_Glass_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.02, 2.0)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['Mat_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.11, 0.5, 1.08))
obj = bpy.context.active_object
obj.name = 'Shower_Glass_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.9, 2.0)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Mat_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, 0.04, 1.28))
obj = bpy.context.active_object
obj.name = 'Shower_Handle'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.04, 0.03)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.03, location=(1.55, 0.94, 1.2))
obj = bpy.context.active_object
obj.name = 'Shower_Valve'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.08, depth=0.02, location=(1.55, 0.94, 2.2))
obj = bpy.context.active_object
obj.name = 'Showerhead'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.9, 1.6, 0.85))
obj = bpy.context.active_object
obj.name = 'Sink_Basin'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.45, 0.35, 0.15)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Mat_Porcelain'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.9, 1.5, 0.97))
obj = bpy.context.active_object
obj.name = 'Sink_Faucet_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.1)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.9, 1.58, 1.03))
obj = bpy.context.active_object
obj.name = 'Sink_Faucet_Spout'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.12, 0.03)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 1.77, 1.25))
obj = bpy.context.active_object
obj.name = 'Tile_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.0, 0.02, 2.5)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Mat_Tile_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.97, 0.9, 1.25))
obj = bpy.context.active_object
obj.name = 'Tile_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 1.8, 2.5)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Mat_Tile_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.35, 1.5, 0.35))
obj = bpy.context.active_object
obj.name = 'Toilet_Bowl'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.38, 0.4, 0.18)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Mat_Porcelain'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.35, 1.74, 0.55))
obj = bpy.context.active_object
obj.name = 'Toilet_Cistern'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.4, 0.12, 1.1)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.35, 1.68, 0.85))
obj = bpy.context.active_object
obj.name = 'Toilet_Flush_Button'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.02, 0.06)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.05, depth=0.1, location=(0.12, 1.5, 0.55))
obj = bpy.context.active_object
obj.name = 'Toilet_Paper'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['Mat_Toilet_Paper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.02, depth=0.11, location=(0.12, 1.5, 0.55))
obj = bpy.context.active_object
obj.name = 'Toilet_Paper_Core'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['Mat_Floor_Beige'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.234, depth=0.03, location=(0.35, 1.45, 0.46))
obj = bpy.context.active_object
obj.name = 'Toilet_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.769231, 1.0, 1.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['Mat_Porcelain'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.012, depth=0.8, location=(0.54, 1.72, 0.7))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.012, depth=0.8, location=(0.7, 1.72, 0.7))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 0.4))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_1'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 0.52))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_2'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 0.64))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_3'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 0.76))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_4'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 0.88))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_5'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.008, depth=0.16, location=(0.62, 1.72, 1.0))
obj = bpy.context.active_object
obj.name = 'Towel_Rail_Rung_6'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.08, depth=0.24, location=(0.75, 1.4, 0.12))
obj = bpy.context.active_object
obj.name = 'Trash_Can_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.085, depth=0.02, location=(0.75, 1.4, 0.25))
obj = bpy.context.active_object
obj.name = 'Trash_Can_Lid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.025, location=(1.4, 1.3, 2.495))
obj = bpy.context.active_object
obj.name = 'Vent_Fan_Grille'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['Mat_Vent'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.4, 1.3, 2.49))
obj = bpy.context.active_object
obj.name = 'Vent_Fan_Housing'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.18, 0.18, 0.02)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 1.86, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.24, 0.12, 2.5)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Mat_Tile_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.5, 3.06, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Bedroom_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 0.12, 2.5)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.5, -0.06, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Bedroom_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 0.12, 2.5)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.06, 1.5, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Bedroom_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 3.0, 2.5)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, -0.06, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.24, 0.12, 2.5)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 1.45, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.7, 2.5)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 0.15, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.3, 2.5)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.06, 0.9, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 1.8, 2.5)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.5, 1.07))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Bottom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 1.08, 0.06)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 0.99, 1.5))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.8)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 2.01, 1.5))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.8)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.5, 1.93))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 1.08, 0.06)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['Mat_Wall_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.5, 1.5))
obj = bpy.context.active_object
obj.name = 'Window_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 1.0, 0.8)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['Mat_Window_Glass'])

bpy.ops.object.light_add(type='AREA', location=(-2.9, 1.5, 1.5))
obj = bpy.context.active_object
obj.name = 'Window_Light'
obj.rotation_euler = (0.0, -1.570796, 0.0)
obj.data.energy = 100.0
obj.data.color = (0.9, 0.92, 1.0)
obj.data.size = 1.0

# ============================================================
# Parent Relationships
# ============================================================
bpy.data.objects['Door_Handle'].parent = bpy.data.objects['Door_Panel']

