"""
Blender Scene: scene0351_01.blend
Objects: 166
Materials: 39
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.8, 0.8, 0.8, 1.0)
    _bg.inputs['Strength'].default_value = 0.5

# ============================================================
# Materials
# ============================================================
mat_M_Blind = bpy.data.materials.new(name='M_Blind')
mat_M_Blind.use_nodes = True
_bsdf = mat_M_Blind.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.8, 0.78, 0.72, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_BlindDark = bpy.data.materials.new(name='M_BlindDark')
mat_M_BlindDark.use_nodes = True
_bsdf = mat_M_BlindDark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.1, 0.1, 0.1, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Book = bpy.data.materials.new(name='M_Book')
mat_M_Book.use_nodes = True
_bsdf = mat_M_Book.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.55, 0.25, 0.15, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Book2 = bpy.data.materials.new(name='M_Book2')
mat_M_Book2.use_nodes = True
_bsdf = mat_M_Book2.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.2, 0.35, 0.55, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Book3 = bpy.data.materials.new(name='M_Book3')
mat_M_Book3.use_nodes = True
_bsdf = mat_M_Book3.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.35, 0.5, 0.28, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Bottle = bpy.data.materials.new(name='M_Bottle')
mat_M_Bottle.use_nodes = True
_bsdf = mat_M_Bottle.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.2, 0.5, 0.75, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.6
mat_M_Bottle.blend_method = 'BLEND'

mat_M_Cabinet = bpy.data.materials.new(name='M_Cabinet')
mat_M_Cabinet.use_nodes = True
_bsdf = mat_M_Cabinet.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.82, 0.77, 0.62, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_CabinetDk = bpy.data.materials.new(name='M_CabinetDk')
mat_M_CabinetDk.use_nodes = True
_bsdf = mat_M_CabinetDk.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.28, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Ceiling_TP = bpy.data.materials.new(name='M_Ceiling_TP')
mat_M_Ceiling_TP.use_nodes = True
_bsdf = mat_M_Ceiling_TP.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.93, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.3
mat_M_Ceiling_TP.blend_method = 'BLEND'

mat_M_ChairDark = bpy.data.materials.new(name='M_ChairDark')
mat_M_ChairDark.use_nodes = True
_bsdf = mat_M_ChairDark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.1, 0.14, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.75
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_ChairMetal = bpy.data.materials.new(name='M_ChairMetal')
mat_M_ChairMetal.use_nodes = True
_bsdf = mat_M_ChairMetal.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.2, 0.2, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.8

mat_M_ChairNavy = bpy.data.materials.new(name='M_ChairNavy')
mat_M_ChairNavy.use_nodes = True
_bsdf = mat_M_ChairNavy.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.1, 0.14, 0.28, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Corkboard = bpy.data.materials.new(name='M_Corkboard')
mat_M_Corkboard.use_nodes = True
_bsdf = mat_M_Corkboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.58, 0.38, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Crate = bpy.data.materials.new(name='M_Crate')
mat_M_Crate.use_nodes = True
_bsdf = mat_M_Crate.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.45, 0.3, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Curtain = bpy.data.materials.new(name='M_Curtain')
mat_M_Curtain.use_nodes = True
_bsdf = mat_M_Curtain.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.58, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Desk = bpy.data.materials.new(name='M_Desk')
mat_M_Desk.use_nodes = True
_bsdf = mat_M_Desk.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.78, 0.7, 0.52, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_DeskEdge = bpy.data.materials.new(name='M_DeskEdge')
mat_M_DeskEdge.use_nodes = True
_bsdf = mat_M_DeskEdge.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.12, 0.12, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Fan = bpy.data.materials.new(name='M_Fan')
mat_M_Fan.use_nodes = True
_bsdf = mat_M_Fan.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.08, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_FanGrid = bpy.data.materials.new(name='M_FanGrid')
mat_M_FanGrid.use_nodes = True
_bsdf = mat_M_FanGrid.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.25, 0.25, 0.25, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Floor = bpy.data.materials.new(name='M_Floor')
mat_M_Floor.use_nodes = True
_bsdf = mat_M_Floor.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.15, 0.18, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Fluorescent = bpy.data.materials.new(name='M_Fluorescent')
mat_M_Fluorescent.use_nodes = True
_bsdf = mat_M_Fluorescent.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.98, 0.98, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Keyboard = bpy.data.materials.new(name='M_Keyboard')
mat_M_Keyboard.use_nodes = True
_bsdf = mat_M_Keyboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.1, 0.1, 0.1, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Laptop = bpy.data.materials.new(name='M_Laptop')
mat_M_Laptop.use_nodes = True
_bsdf = mat_M_Laptop.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.15, 0.15, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.35
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_LightCover = bpy.data.materials.new(name='M_LightCover')
mat_M_LightCover.use_nodes = True
_bsdf = mat_M_LightCover.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.92, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.6
mat_M_LightCover.blend_method = 'BLEND'

mat_M_Monitor = bpy.data.materials.new(name='M_Monitor')
mat_M_Monitor.use_nodes = True
_bsdf = mat_M_Monitor.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.05, 0.05, 0.05, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Papers = bpy.data.materials.new(name='M_Papers')
mat_M_Papers.use_nodes = True
_bsdf = mat_M_Papers.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.93, 0.91, 0.87, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Phone = bpy.data.materials.new(name='M_Phone')
mat_M_Phone.use_nodes = True
_bsdf = mat_M_Phone.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.65, 0.62, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_PlantLeaves = bpy.data.materials.new(name='M_PlantLeaves')
mat_M_PlantLeaves.use_nodes = True
_bsdf = mat_M_PlantLeaves.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.22, 0.45, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_PlantPot = bpy.data.materials.new(name='M_PlantPot')
mat_M_PlantPot.use_nodes = True
_bsdf = mat_M_PlantPot.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.18, 0.45, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_PlantStem = bpy.data.materials.new(name='M_PlantStem')
mat_M_PlantStem.use_nodes = True
_bsdf = mat_M_PlantStem.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.22, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Radiator = bpy.data.materials.new(name='M_Radiator')
mat_M_Radiator.use_nodes = True
_bsdf = mat_M_Radiator.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.85, 0.84, 0.8, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Screen = bpy.data.materials.new(name='M_Screen')
mat_M_Screen.use_nodes = True
_bsdf = mat_M_Screen.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.2, 0.25, 0.35, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.1
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_SmallTable = bpy.data.materials.new(name='M_SmallTable')
mat_M_SmallTable.use_nodes = True
_bsdf = mat_M_SmallTable.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.78, 0.7, 0.52, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.65
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_TableLeg = bpy.data.materials.new(name='M_TableLeg')
mat_M_TableLeg.use_nodes = True
_bsdf = mat_M_TableLeg.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.12, 0.12, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Wall = bpy.data.materials.new(name='M_Wall')
mat_M_Wall.use_nodes = True
_bsdf = mat_M_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.91, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Watering = bpy.data.materials.new(name='M_Watering')
mat_M_Watering.use_nodes = True
_bsdf = mat_M_Watering.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.25, 0.75, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_WbFrame = bpy.data.materials.new(name='M_WbFrame')
mat_M_WbFrame.use_nodes = True
_bsdf = mat_M_WbFrame.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.55, 0.4, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Whiteboard = bpy.data.materials.new(name='M_Whiteboard')
mat_M_Whiteboard.use_nodes = True
_bsdf = mat_M_Whiteboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.97, 0.97, 0.97, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.2
_bsdf.inputs['Metallic'].default_value = 0.0

mat_M_Window = bpy.data.materials.new(name='M_Window')
mat_M_Window.use_nodes = True
_bsdf = mat_M_Window.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.5, 0.6, 0.7, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.25
mat_M_Window.blend_method = 'BLEND'

# ============================================================
# Objects
# ============================================================
bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 2.27))
obj = bpy.context.active_object
obj.name = 'Blind_Rail'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.96, 0.08, 0.08)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.08))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 2.025))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 2.13))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_11'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 2.235))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_12'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.185))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.29))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.395))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.5))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.605))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.71))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.815))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.46, 1.92))
obj = bpy.context.active_object
obj.name = 'Blind_Slat_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.04, 0.05)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['M_Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.75, 2.5, 0.825))
obj = bpy.context.active_object
obj.name = 'Book_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.26, 0.05)
obj.data.name = 'Cube.110'
obj.data.materials.append(bpy.data.materials['M_Book'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.75, 2.5, 0.8725))
obj = bpy.context.active_object
obj.name = 'Book_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.26, 0.045)
obj.data.name = 'Cube.111'
obj.data.materials.append(bpy.data.materials['M_Book2'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.75, 2.5, 0.9225))
obj = bpy.context.active_object
obj.name = 'Book_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.26, 0.055)
obj.data.name = 'Cube.112'
obj.data.materials.append(bpy.data.materials['M_Book3'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.2, location=(-1.0, -0.85, 0.86))
obj = bpy.context.active_object
obj.name = 'Bottle_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.019'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.035, depth=0.18, location=(-1.1, -0.92, 0.86))
obj = bpy.context.active_object
obj.name = 'Bottle_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.020'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, -3.48, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.8, 0.5, 2.2)
obj.data.name = 'Cube.091'
obj.data.materials.append(bpy.data.materials['M_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, -3.22, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Divider'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 2.16)
obj.data.name = 'Cube.094'
obj.data.materials.append(bpy.data.materials['M_CabinetDk'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.52, -3.23, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Door_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.88, 0.04, 2.16)
obj.data.name = 'Cube.092'
obj.data.materials.append(bpy.data.materials['M_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.48, -3.23, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Door_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.88, 0.04, 2.16)
obj.data.name = 'Cube.093'
obj.data.materials.append(bpy.data.materials['M_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.68, -3.21, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Handle_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.16)
obj.data.name = 'Cube.095'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.32, -3.21, 1.1))
obj = bpy.context.active_object
obj.name = 'Cabinet_Handle_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.16)
obj.data.name = 'Cube.096'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.0, -3.48, 2.22))
obj = bpy.context.active_object
obj.name = 'Cabinet_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.82, 0.52, 0.06)
obj.data.name = 'Cube.097'
obj.data.materials.append(bpy.data.materials['M_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.98, -1.6, 1.4))
obj = bpy.context.active_object
obj.name = 'Calendar_Board'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.6, 0.44)
obj.data.name = 'Cube.081'
obj.data.materials.append(bpy.data.materials['M_Whiteboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.96, -1.6, 1.4))
obj = bpy.context.active_object
obj.name = 'Calendar_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.48)
obj.data.name = 'Cube.082'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.object.camera_add(location=(-1.5, -2.8, 1.4))
obj = bpy.context.active_object
obj.name = 'Camera'
obj.rotation_euler = (1.396263, 0.0, -0.523599)
obj.data.lens = 24.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.98, 1.5, 1.5))
obj = bpy.context.active_object
obj.name = 'Corkboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.9, 0.7)
obj.data.name = 'Cube.079'
obj.data.materials.append(bpy.data.materials['M_Corkboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.95, 1.5, 1.5))
obj = bpy.context.active_object
obj.name = 'Corkboard_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.94, 0.74)
obj.data.name = 'Cube.080'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, -1.6, 0.12))
obj = bpy.context.active_object
obj.name = 'Crate_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.36, 0.24)
obj.data.name = 'Cube.118'
obj.data.materials.append(bpy.data.materials['M_Crate'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.58, -1.67, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_0_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.029'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.58, -1.49, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_0_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.030'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.43, -1.67, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_1_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.031'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.43, -1.49, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_1_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.032'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.28, -1.67, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_2_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.033'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.14, location=(-0.28, -1.49, 0.27))
obj = bpy.context.active_object
obj.name = 'Crate_Bottle_2_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.034'
obj.data.materials.append(bpy.data.materials['M_Bottle'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.6, 3.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Curtain'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.2, 2.8)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['M_Curtain'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.55, 2.0, 0.37))
obj = bpy.context.active_object
obj.name = 'Desk_Drawer_Unit'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.4, 0.6, 0.74)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['M_Desk'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 1.38, 0.74))
obj = bpy.context.active_object
obj.name = 'Desk_Edge_Main_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.6, 0.04, 0.1)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['M_DeskEdge'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.78, 0.6, 0.74))
obj = bpy.context.active_object
obj.name = 'Desk_Edge_Side_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 1.6, 0.1)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['M_DeskEdge'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.28, 1.5, 0.37))
obj = bpy.context.active_object
obj.name = 'Desk_Leg_0.28_1.50'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.08, 0.74)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['M_DeskEdge'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.72, 1.5, 0.37))
obj = bpy.context.active_object
obj.name = 'Desk_Leg_2.72_1.50'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.08, 0.74)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['M_DeskEdge'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.72, 3.2, 0.37))
obj = bpy.context.active_object
obj.name = 'Desk_Leg_2.72_3.20'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.08, 0.74)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['M_DeskEdge'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.3, 2.5, 0.812))
obj = bpy.context.active_object
obj.name = 'Desk_Notebook'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.28, 0.024)
obj.data.name = 'Cube.117'
obj.data.materials.append(bpy.data.materials['M_Keyboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.35, 0.37))
obj = bpy.context.active_object
obj.name = 'Desk_Panel_Main'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.56, 0.04, 0.74)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['M_Desk'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.4, 2.55, 0.805))
obj = bpy.context.active_object
obj.name = 'Desk_Papers_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.4, 0.3, 0.016)
obj.data.name = 'Cube.115'
obj.data.materials.append(bpy.data.materials['M_Papers'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2, 2.6, 0.805))
obj = bpy.context.active_object
obj.name = 'Desk_Papers_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.36, 0.26, 0.012)
obj.data.name = 'Cube.116'
obj.data.materials.append(bpy.data.materials['M_Papers'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.35, 0.76))
obj = bpy.context.active_object
obj.name = 'Desk_Top_Main'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.6, 1.9, 0.08)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['M_Desk'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.4, 0.6, 0.76))
obj = bpy.context.active_object
obj.name = 'Desk_Top_Side'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 1.6, 0.08)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['M_Desk'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -1.0, 0.49))
obj = bpy.context.active_object
obj.name = 'Fan_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.16, 0.04)
obj.data.name = 'Cube.072'
obj.data.materials.append(bpy.data.materials['M_Fan'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.9, -1.0, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Blade_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.04, 0.01)
obj.data.name = 'Cube.068'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.1, -1.0, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Blade_180'
obj.rotation_euler = (0.0, 0.0, 3.141593)
obj.scale = (0.16, 0.04, 0.01)
obj.data.name = 'Cube.070'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -1.1, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Blade_270'
obj.rotation_euler = (0.0, 0.0, 4.712389)
obj.scale = (0.16, 0.04, 0.01)
obj.data.name = 'Cube.071'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -0.9, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Blade_90'
obj.rotation_euler = (0.0, 0.0, 1.570796)
obj.scale = (0.16, 0.04, 0.01)
obj.data.name = 'Cube.069'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.16, depth=0.06, location=(-2.0, -1.0, 0.62))
obj = bpy.context.active_object
obj.name = 'Fan_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['M_Fan'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.17, depth=0.01, location=(-2.0, -1.0, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Guard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(-2.0, -1.0, 0.65))
obj = bpy.context.active_object
obj.name = 'Fan_Hub'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['M_FanGrid'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.12, location=(-2.0, -1.0, 0.53))
obj = bpy.context.active_object
obj.name = 'Fan_Stand'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['M_Fan'])

bpy.ops.object.light_add(type='AREA', location=(-1.5, -1.0, 2.5))
obj = bpy.context.active_object
obj.name = 'Fill_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 200.0
obj.data.size = 2.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.075))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 7.0, 0.15)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['M_Floor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, -1.2, 2.95))
obj = bpy.context.active_object
obj.name = 'Fluor_Body_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.3, 0.06)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['M_Fluorescent'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, 1.2, 2.95))
obj = bpy.context.active_object
obj.name = 'Fluor_Body_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.3, 0.06)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['M_Fluorescent'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, -1.2, 2.92))
obj = bpy.context.active_object
obj.name = 'Fluor_Cover_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 1.32, 0.04)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['M_LightCover'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, 1.2, 2.92))
obj = bpy.context.active_object
obj.name = 'Fluor_Cover_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 1.32, 0.04)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['M_LightCover'])

bpy.ops.object.light_add(type='AREA', location=(0.5, -1.2, 2.85))
obj = bpy.context.active_object
obj.name = 'Fluor_Light_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 400.0
obj.data.color = (1.0, 0.98, 0.9)
obj.data.size = 1.2

bpy.ops.object.light_add(type='AREA', location=(0.5, 1.2, 2.85))
obj = bpy.context.active_object
obj.name = 'Fluor_Light_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 400.0
obj.data.color = (1.0, 0.98, 0.9)
obj.data.size = 1.2

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 2.42, 0.81))
obj = bpy.context.active_object
obj.name = 'Keyboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.18, 0.03)
obj.data.name = 'Cube.106'
obj.data.materials.append(bpy.data.materials['M_Keyboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, 2.5, 0.81))
obj = bpy.context.active_object
obj.name = 'Laptop_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.38, 0.28, 0.03)
obj.data.name = 'Cube.108'
obj.data.materials.append(bpy.data.materials['M_Laptop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, 2.38, 0.93))
obj = bpy.context.active_object
obj.name = 'Laptop_Screen'
obj.rotation_euler = (-0.349066, 0.0, 0.0)
obj.scale = (0.36, 0.02, 0.28)
obj.data.name = 'Cube.109'
obj.data.materials.append(bpy.data.materials['M_Laptop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.65, 2.79, 1.05))
obj = bpy.context.active_object
obj.name = 'Mon1_Display'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.66, 0.04, 0.5)
obj.data.name = 'Cube.099'
obj.data.materials.append(bpy.data.materials['M_Screen'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.65, 2.8, 1.05))
obj = bpy.context.active_object
obj.name = 'Mon1_Screen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.7, 0.08, 0.54)
obj.data.name = 'Cube.098'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.65, 2.72, 0.8))
obj = bpy.context.active_object
obj.name = 'Mon1_Stand_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.28, 0.2, 0.05)
obj.data.name = 'Cube.101'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.65, 2.72, 0.84))
obj = bpy.context.active_object
obj.name = 'Mon1_Stand_Neck'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.12, 0.24)
obj.data.name = 'Cube.100'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.77, 1.08))
obj = bpy.context.active_object
obj.name = 'Mon2_Display'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.62, 0.04, 0.48)
obj.data.name = 'Cube.103'
obj.data.materials.append(bpy.data.materials['M_Screen'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.78, 1.08))
obj = bpy.context.active_object
obj.name = 'Mon2_Screen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.66, 0.08, 0.52)
obj.data.name = 'Cube.102'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.7, 0.82))
obj = bpy.context.active_object
obj.name = 'Mon2_Stand_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.26, 0.18, 0.05)
obj.data.name = 'Cube.105'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.7, 0.87))
obj = bpy.context.active_object
obj.name = 'Mon2_Stand_Neck'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.12, 0.2)
obj.data.name = 'Cube.104'
obj.data.materials.append(bpy.data.materials['M_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.15, 2.42, 0.81))
obj = bpy.context.active_object
obj.name = 'Mouse'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.12, 0.04)
obj.data.name = 'Cube.107'
obj.data.materials.append(bpy.data.materials['M_Keyboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.74, 1.93, 0.6))
obj = bpy.context.active_object
obj.name = 'OChair1_Arm_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.28, 0.08)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.26, 1.93, 0.6))
obj = bpy.context.active_object
obj.name = 'OChair1_Arm_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.28, 0.08)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 2.07, 0.75))
obj = bpy.context.active_object
obj.name = 'OChair1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.06, 0.44)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.04, location=(1.0, 1.85, 0.05))
obj = bpy.context.active_object
obj.name = 'OChair1_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 1.85, 0.55))
obj = bpy.context.active_object
obj.name = 'OChair1_Cushion'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.44, 0.06)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['M_ChairNavy'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 1.85, 0.5))
obj = bpy.context.active_object
obj.name = 'OChair1_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.48, 0.48, 0.1)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['M_ChairNavy'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.5, location=(1.0, 1.85, 0.25))
obj = bpy.context.active_object
obj.name = 'OChair1_Stem'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(1.28, 1.85, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair1_Wheel_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(0.773475, 2.01458, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair1_Wheel_144'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(0.773475, 1.68542, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair1_Wheel_216'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(1.086525, 1.583704, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair1_Wheel_288'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(1.086525, 2.116296, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair1_Wheel_72'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, 0.28, 0.6))
obj = bpy.context.active_object
obj.name = 'OChair2_Arm_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.26, 0.08)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.6, 0.28, 0.6))
obj = bpy.context.active_object
obj.name = 'OChair2_Arm_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.26, 0.08)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.35, 0.42, 0.75))
obj = bpy.context.active_object
obj.name = 'OChair2_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.06, 0.44)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.27, depth=0.04, location=(2.35, 0.2, 0.05))
obj = bpy.context.active_object
obj.name = 'OChair2_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.35, 0.2, 0.55))
obj = bpy.context.active_object
obj.name = 'OChair2_Cushion'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.42, 0.06)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['M_ChairNavy'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.35, 0.2, 0.5))
obj = bpy.context.active_object
obj.name = 'OChair2_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.1)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.5, location=(2.35, 0.2, 0.25))
obj = bpy.context.active_object
obj.name = 'OChair2_Stem'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['M_ChairMetal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(2.62, 0.2, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair2_Wheel_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(2.131565, 0.358702, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair2_Wheel_144'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(2.131565, 0.041298, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair2_Wheel_216'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(2.433434, -0.056785, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair2_Wheel_288'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.04, location=(2.433434, 0.456785, 0.03))
obj = bpy.context.active_object
obj.name = 'OChair2_Wheel_72'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.45, 2.85, 0.82))
obj = bpy.context.active_object
obj.name = 'Phone_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.26, 0.08)
obj.data.name = 'Cube.113'
obj.data.materials.append(bpy.data.materials['M_Phone'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.42, 2.85, 0.87))
obj = bpy.context.active_object
obj.name = 'Phone_Handset'
obj.rotation_euler = (0.0, 0.174533, 0.0)
obj.scale = (0.12, 0.24, 0.05)
obj.data.name = 'Cube.114'
obj.data.materials.append(bpy.data.materials['M_Phone'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.0, -0.6, 0.8))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.023'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.31, -0.409474, 0.85))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_120'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.025'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.39, -0.6, 0.88))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_180'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.026'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.305, -0.781865, 0.83))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_240'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.027'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.115, -0.747224, 0.92))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_300'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.028'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.3, location=(-2.11, -0.444115, 0.9))
obj = bpy.context.active_object
obj.name = 'Plant_Branch_60'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.024'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.0, -0.6, 1.02))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.31, -0.409474, 1.07))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_120'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.002'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.39, -0.6, 1.1))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_180'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.003'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.305, -0.781865, 1.05))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_240'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.004'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.115, -0.747224, 1.14))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_300'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.005'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.22, location=(-2.11, -0.444115, 1.12))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_60'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.001'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.25, location=(-2.2, -0.6, 0.85))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_Mid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.007'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.3, location=(-2.2, -0.6, 1.1))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.006'
obj.data.materials.append(bpy.data.materials['M_PlantLeaves'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.18, depth=0.36, location=(-2.2, -0.6, 0.18))
obj = bpy.context.active_object
obj.name = 'Plant_Pot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.021'
obj.data.materials.append(bpy.data.materials['M_PlantPot'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.55, location=(-2.2, -0.6, 0.55))
obj = bpy.context.active_object
obj.name = 'Plant_Stem'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.022'
obj.data.materials.append(bpy.data.materials['M_PlantStem'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.28, 0.03))
obj = bpy.context.active_object
obj.name = 'Radiator_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.24, 0.06)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.9, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.62, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.34, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.06, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.22, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, 3.28, 0.25))
obj = bpy.context.active_object
obj.name = 'Radiator_Fin_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.2, 0.5)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.28, 0.52))
obj = bpy.context.active_object
obj.name = 'Radiator_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.9, 0.24, 0.06)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['M_Radiator'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -0.78, 0.65))
obj = bpy.context.active_object
obj.name = 'SChair1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.06, 0.4)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, -0.8, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair1_Leg_-1.8_-0.8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.8, -1.2, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair1_Leg_-1.8_-1.2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.2, -0.8, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair1_Leg_-2.2_-0.8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.2, -1.2, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair1_Leg_-2.2_-1.2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -1.0, 0.46))
obj = bpy.context.active_object
obj.name = 'SChair1_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.42, 0.08)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.8, -1.58, 0.65))
obj = bpy.context.active_object
obj.name = 'SChair2_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.06, 0.4)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.6, -1.6, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair2_Leg_-0.6_-1.6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.6, -2.0, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair2_Leg_-0.6_-2.0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, -1.6, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair2_Leg_-1.0_-1.6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.067'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, -2.0, 0.23))
obj = bpy.context.active_object
obj.name = 'SChair2_Leg_-1.0_-2.0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.46)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.8, -1.8, 0.46))
obj = bpy.context.active_object
obj.name = 'SChair2_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.42, 0.08)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['M_ChairDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, -0.65, 0.37))
obj = bpy.context.active_object
obj.name = 'STable_Leg_-0.45_-0.65'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.74)
obj.data.name = 'Cube.086'
obj.data.materials.append(bpy.data.materials['M_TableLeg'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, -1.35, 0.37))
obj = bpy.context.active_object
obj.name = 'STable_Leg_-0.45_-1.35'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.74)
obj.data.name = 'Cube.085'
obj.data.materials.append(bpy.data.materials['M_TableLeg'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.55, -0.65, 0.37))
obj = bpy.context.active_object
obj.name = 'STable_Leg_-1.55_-0.65'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.74)
obj.data.name = 'Cube.087'
obj.data.materials.append(bpy.data.materials['M_TableLeg'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.55, -1.35, 0.37))
obj = bpy.context.active_object
obj.name = 'STable_Leg_-1.55_-1.35'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.74)
obj.data.name = 'Cube.084'
obj.data.materials.append(bpy.data.materials['M_TableLeg'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, -1.0, 0.28))
obj = bpy.context.active_object
obj.name = 'STable_Shelf'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.16, 0.72, 0.05)
obj.data.name = 'Cube.088'
obj.data.materials.append(bpy.data.materials['M_SmallTable'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, -1.0, 0.76))
obj = bpy.context.active_object
obj.name = 'STable_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 0.76, 0.08)
obj.data.name = 'Cube.083'
obj.data.materials.append(bpy.data.materials['M_SmallTable'])

bpy.ops.object.light_add(type='SUN', location=(0.0, 4.0, 5.0))
obj = bpy.context.active_object
obj.name = 'Sun_Window'
obj.rotation_euler = (1.047198, 0.0, -0.523599)
obj.data.energy = 1.5

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.2, -1.05, 0.8))
obj = bpy.context.active_object
obj.name = 'Table_Papers'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.36, 0.28, 0.04)
obj.data.name = 'Cube.090'
obj.data.materials.append(bpy.data.materials['M_Papers'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 3.575, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 0.15, 3.0)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['M_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -3.575, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 0.15, 3.0)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['M_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.075, 0.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 7.0, 3.0)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['M_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.075, 0.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 7.0, 3.0)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['M_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.75, -0.9, 0.82))
obj = bpy.context.active_object
obj.name = 'Watering_Can'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.12, 0.2)
obj.data.name = 'Cube.089'
obj.data.materials.append(bpy.data.materials['M_Watering'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.03, location=(-0.68, -0.84, 0.9))
obj = bpy.context.active_object
obj.name = 'Watering_Spout'
obj.rotation_euler = (-1.570796, -0.785398, 0.785398)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['M_Watering'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.98, 1.2, 1.45))
obj = bpy.context.active_object
obj.name = 'Whiteboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 2.6, 1.5)
obj.data.name = 'Cube.073'
obj.data.materials.append(bpy.data.materials['M_Whiteboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.2, 0.68))
obj = bpy.context.active_object
obj.name = 'Whiteboard_Frame_Bottom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 2.64, 0.08)
obj.data.name = 'Cube.075'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, -0.12, 1.45))
obj = bpy.context.active_object
obj.name = 'Whiteboard_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.08, 1.58)
obj.data.name = 'Cube.076'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 2.52, 1.45))
obj = bpy.context.active_object
obj.name = 'Whiteboard_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.08, 1.58)
obj.data.name = 'Cube.077'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.2, 2.22))
obj = bpy.context.active_object
obj.name = 'Whiteboard_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 2.64, 0.08)
obj.data.name = 'Cube.074'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.94, 1.2, 0.72))
obj = bpy.context.active_object
obj.name = 'Whiteboard_Tray'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 2.6, 0.06)
obj.data.name = 'Cube.078'
obj.data.materials.append(bpy.data.materials['M_WbFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.48, 1.0))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Bottom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.16, 0.12)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.55, 3.48, 1.65))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.16, 1.3)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.55, 3.48, 1.65))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.16, 1.3)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.48, 2.3))
obj = bpy.context.active_object
obj.name = 'Window_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.16, 0.12)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['M_BlindDark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.5, 3.48, 1.65))
obj = bpy.context.active_object
obj.name = 'Window_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.0, 0.08, 1.2)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['M_Window'])

