"""
Blender Scene: scene0307_00.blend
Objects: 125
Materials: 24
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.04, 0.04, 0.04, 1.0)
    _bg.inputs['Strength'].default_value = 0.3

# ============================================================
# Materials
# ============================================================
mat_Mat_Basket = bpy.data.materials.new(name='Mat_Basket')
mat_Mat_Basket.use_nodes = True
_bsdf = mat_Mat_Basket.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.58, 0.4, 0.18, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Beige_Fabric = bpy.data.materials.new(name='Mat_Beige_Fabric')
mat_Mat_Beige_Fabric.use_nodes = True
_bsdf = mat_Mat_Beige_Fabric.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.62, 0.52, 0.35, 1.0)
_bsdf.inputs['Roughness'].default_value = 1.0
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Blue_Tile = bpy.data.materials.new(name='Mat_Blue_Tile')
mat_Mat_Blue_Tile.use_nodes = True
_bsdf = mat_Mat_Blue_Tile.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.22, 0.52, 0.7, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Cardboard = bpy.data.materials.new(name='Mat_Cardboard')
mat_Mat_Cardboard.use_nodes = True
_bsdf = mat_Mat_Cardboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.66, 0.5, 0.3, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Ceiling = bpy.data.materials.new(name='Mat_Ceiling')
mat_Mat_Ceiling.use_nodes = True
_bsdf = mat_Mat_Ceiling.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.62, 0.62, 0.58, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.35
mat_Mat_Ceiling.blend_method = 'BLEND'

mat_Mat_Dark_Ins = bpy.data.materials.new(name='Mat_Dark_Ins')
mat_Mat_Dark_Ins.use_nodes = True
_bsdf = mat_Mat_Dark_Ins.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.08, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Door_Gray = bpy.data.materials.new(name='Mat_Door_Gray')
mat_Mat_Door_Gray.use_nodes = True
_bsdf = mat_Mat_Door_Gray.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.73, 0.7, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Floor_Terra = bpy.data.materials.new(name='Mat_Floor_Terra')
mat_Mat_Floor_Terra.use_nodes = True
_bsdf = mat_Mat_Floor_Terra.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.52, 0.31, 0.16, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Floor_Tile = bpy.data.materials.new(name='Mat_Floor_Tile')
mat_Mat_Floor_Tile.use_nodes = True
_bsdf = mat_Mat_Floor_Tile.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.7, 0.65, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Frosted = bpy.data.materials.new(name='Mat_Frosted')
mat_Mat_Frosted.use_nodes = True
_bsdf = mat_Mat_Frosted.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.8, 0.85, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.45
mat_Mat_Frosted.blend_method = 'BLEND'

mat_Mat_Green_Cloth = bpy.data.materials.new(name='Mat_Green_Cloth')
mat_Mat_Green_Cloth.use_nodes = True
_bsdf = mat_Mat_Green_Cloth.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.4, 0.17, 1.0)
_bsdf.inputs['Roughness'].default_value = 1.0
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Metal_Copper = bpy.data.materials.new(name='Mat_Metal_Copper')
mat_Mat_Metal_Copper.use_nodes = True
_bsdf = mat_Mat_Metal_Copper.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.42, 0.17, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.25
_bsdf.inputs['Metallic'].default_value = 0.95

mat_Mat_Metal_Gray = bpy.data.materials.new(name='Mat_Metal_Gray')
mat_Mat_Metal_Gray.use_nodes = True
_bsdf = mat_Mat_Metal_Gray.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.38, 0.38, 0.38, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.9

mat_Mat_Orange_Pot = bpy.data.materials.new(name='Mat_Orange_Pot')
mat_Mat_Orange_Pot.use_nodes = True
_bsdf = mat_Mat_Orange_Pot.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.36, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Pipe_Dark = bpy.data.materials.new(name='Mat_Pipe_Dark')
mat_Mat_Pipe_Dark.use_nodes = True
_bsdf = mat_Mat_Pipe_Dark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.12, 0.12, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.45
_bsdf.inputs['Metallic'].default_value = 0.6

mat_Mat_Red_Boiler = bpy.data.materials.new(name='Mat_Red_Boiler')
mat_Mat_Red_Boiler.use_nodes = True
_bsdf = mat_Mat_Red_Boiler.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.62, 0.07, 0.05, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.45
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Red_Plastic = bpy.data.materials.new(name='Mat_Red_Plastic')
mat_Mat_Red_Plastic.use_nodes = True
_bsdf = mat_Mat_Red_Plastic.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.12, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Shelf_White = bpy.data.materials.new(name='Mat_Shelf_White')
mat_Mat_Shelf_White.use_nodes = True
_bsdf = mat_Mat_Shelf_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Teal_Plastic = bpy.data.materials.new(name='Mat_Teal_Plastic')
mat_Mat_Teal_Plastic.use_nodes = True
_bsdf = mat_Mat_Teal_Plastic.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.45, 0.4, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Wall = bpy.data.materials.new(name='Mat_Wall')
mat_Mat_Wall.use_nodes = True
_bsdf = mat_Mat_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.87, 0.85, 0.8, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_White = bpy.data.materials.new(name='Mat_White')
mat_Mat_White.use_nodes = True
_bsdf = mat_Mat_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_White_Tile = bpy.data.materials.new(name='Mat_White_Tile')
mat_Mat_White_Tile.use_nodes = True
_bsdf = mat_Mat_White_Tile.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.9, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Wood_Dark = bpy.data.materials.new(name='Mat_Wood_Dark')
mat_Mat_Wood_Dark.use_nodes = True
_bsdf = mat_Mat_Wood_Dark.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.28, 0.16, 0.07, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Wood_Med = bpy.data.materials.new(name='Mat_Wood_Med')
mat_Mat_Wood_Med.use_nodes = True
_bsdf = mat_Mat_Wood_Med.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.52, 0.33, 0.14, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.88
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.95, -1.2, 1.35))
obj = bpy.context.active_object
obj.name = 'Backsplash_Kitchen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 1.2, 0.55)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Mat_White_Tile'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.38, depth=1.8, location=(-2.2, 2.2, 0.9))
obj = bpy.context.active_object
obj.name = 'Boiler_1_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['Mat_Red_Boiler'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.38, location=(-2.2, 2.2, 0.0))
obj = bpy.context.active_object
obj.name = 'Boiler_1_Cap_B'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.001'
obj.data.materials.append(bpy.data.materials['Mat_Red_Boiler'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.38, location=(-2.2, 2.2, 1.8))
obj = bpy.context.active_object
obj.name = 'Boiler_1_Cap_T'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere'
obj.data.materials.append(bpy.data.materials['Mat_Red_Boiler'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.04, location=(-2.58, 2.2, 0.8))
obj = bpy.context.active_object
obj.name = 'Boiler_1_Gauge'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.object.camera_add(location=(0.5, -1.8, 1.3))
obj = bpy.context.active_object
obj.name = 'Camera'
obj.rotation_euler = (1.396263, 0.0, 0.20944)
obj.data.lens = 18.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.object.light_add(type='AREA', location=(0.0, 1.0, 2.32))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 200.0
obj.data.size = 3.0

bpy.ops.object.light_add(type='AREA', location=(0.0, 0.0, 2.32))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light_Main'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 350.0
obj.data.size = 4.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 1.09, 0.8))
obj = bpy.context.active_object
obj.name = 'Chair_1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.045, 0.6)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 0.86, 0.5))
obj = bpy.context.active_object
obj.name = 'Chair_1_Cloth'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.43, 0.42, 0.04)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['Mat_Green_Cloth'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.62, 0.73, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_1_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.46)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.98, 0.73, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_1_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.46)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.62, 1.07, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_1_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.46)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.98, 1.07, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_1_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.46)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 1.09, 1.08))
obj = bpy.context.active_object
obj.name = 'Chair_1_Rail'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.38, 0.04, 0.04)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, 0.9, 0.46))
obj = bpy.context.active_object
obj.name = 'Chair_1_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.4, 0.045)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Dark'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.3, -1.6, 0.2))
obj = bpy.context.active_object
obj.name = 'Crate_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.34, 0.34, 0.4)
obj.data.name = 'Cube.078'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, -2.54, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_1_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.1, 1.1)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.12, location=(0.72, -2.5, 1.0))
obj = bpy.context.active_object
obj.name = 'Door_1_Handle'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, -2.54, 0.98))
obj = bpy.context.active_object
obj.name = 'Door_1_Panel'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.48, 0.08, 1.02)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['Mat_Door_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, -2.54, 1.72))
obj = bpy.context.active_object
obj.name = 'Door_1_Window'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.05, 0.16)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Mat_Frosted'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.18))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.3))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.067'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.42))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.068'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.54))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.069'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.66))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.070'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.78))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.071'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.275, 0.9))
obj = bpy.context.active_object
obj.name = 'DR_1_Rung_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.55, 0.02)
obj.data.name = 'Cube.072'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 0.0, 0.5))
obj = bpy.context.active_object
obj.name = 'DR_1_Side_L_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.95)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, -0.55, 0.5))
obj = bpy.context.active_object
obj.name = 'DR_1_Side_L_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.95)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.6, 0.0, 0.5))
obj = bpy.context.active_object
obj.name = 'DR_1_Side_R_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.95)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.6, -0.55, 0.5))
obj = bpy.context.active_object
obj.name = 'DR_1_Side_R_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.95)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, 0.0, 0.97))
obj = bpy.context.active_object
obj.name = 'DR_1_Top_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.95, 0.04, 0.04)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.15, -0.55, 0.97))
obj = bpy.context.active_object
obj.name = 'DR_1_Top_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.95, 0.04, 0.04)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.95, -0.8, 1.5))
obj = bpy.context.active_object
obj.name = 'Elec_Box_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.2, 0.28)
obj.data.name = 'Cube.089'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.92, -0.8, 1.5))
obj = bpy.context.active_object
obj.name = 'Elec_Cover_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.025, 0.22, 0.3)
obj.data.name = 'Cube.090'
obj.data.materials.append(bpy.data.materials['Mat_Door_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.08, location=(-1.15, 2.44, 1.58))
obj = bpy.context.active_object
obj.name = 'EV_1_Bolt'
obj.rotation_euler = (1.570796, -0.0, 1.570796)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.25, location=(-1.15, 2.42, 1.22))
obj = bpy.context.active_object
obj.name = 'EV_1_Pipe'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.27, location=(-1.15, 2.42, 1.58))
obj = bpy.context.active_object
obj.name = 'EV_1_Sphere'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.002'
obj.data.materials.append(bpy.data.materials['Mat_Red_Boiler'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.06))
obj = bpy.context.active_object
obj.name = 'Floor_Terra'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 5.0, 0.12)
obj.data.name = 'Cube.001'
obj.data.materials.append(bpy.data.materials['Mat_Floor_Terra'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.0, -1.3, -0.055))
obj = bpy.context.active_object
obj.name = 'Floor_Tile_Kitchen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.0, 1.4, 0.11)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Mat_Floor_Tile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.63, 0.25, 0.44))
obj = bpy.context.active_object
obj.name = 'IB_1_Leg_1'
obj.rotation_euler = (0.0, 0.20944, 0.0)
obj.scale = (0.04, 0.04, 0.88)
obj.data.name = 'Cube.074'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.13, 0.25, 0.44))
obj = bpy.context.active_object
obj.name = 'IB_1_Leg_2'
obj.rotation_euler = (0.0, -0.20944, 0.0)
obj.scale = (0.04, 0.04, 0.88)
obj.data.name = 'Cube.075'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 0.25, 0.44))
obj = bpy.context.active_object
obj.name = 'IB_1_Leg_3'
obj.rotation_euler = (0.0, -0.174533, 0.0)
obj.scale = (0.04, 0.04, 0.88)
obj.data.name = 'Cube.076'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.05, 0.25, 0.44))
obj = bpy.context.active_object
obj.name = 'IB_1_Leg_4'
obj.rotation_euler = (0.0, 0.174533, 0.0)
obj.scale = (0.04, 0.04, 0.88)
obj.data.name = 'Cube.077'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.25, 0.25, 0.9))
obj = bpy.context.active_object
obj.name = 'IB_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.3, 0.34, 0.04)
obj.data.name = 'Cube.073'
obj.data.materials.append(bpy.data.materials['Mat_Beige_Fabric'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, -1.15, 0.44))
obj = bpy.context.active_object
obj.name = 'KC_1_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.56, 1.1, 0.44)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.22, location=(-2.63, -1.15, 1.04))
obj = bpy.context.active_object
obj.name = 'KC_1_Faucet'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.01, depth=0.16, location=(-2.63, -1.5, 0.5))
obj = bpy.context.active_object
obj.name = 'KC_1_Handle_1'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.01, depth=0.16, location=(-2.63, -0.8, 0.5))
obj = bpy.context.active_object
obj.name = 'KC_1_Handle_2'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.63, -1.4, 0.87))
obj = bpy.context.active_object
obj.name = 'KC_1_Sink_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.022, 0.38, 0.08)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.63, -0.9, 0.87))
obj = bpy.context.active_object
obj.name = 'KC_1_Sink_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.022, 0.38, 0.08)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.016, depth=0.18, location=(-2.63, -1.21, 1.04))
obj = bpy.context.active_object
obj.name = 'KC_1_Spout'
obj.rotation_euler = (0.872665, 0.0, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, -1.15, 0.91))
obj = bpy.context.active_object
obj.name = 'KC_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.56, 1.1, 0.03)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.55, -1.15, 1.55))
obj = bpy.context.active_object
obj.name = 'KC_Curtain'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.88, 0.48)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.61, -1.15, 1.55))
obj = bpy.context.active_object
obj.name = 'KC_Window_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.9, 0.52)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.6, -1.15, 1.55))
obj = bpy.context.active_object
obj.name = 'KC_Window_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.02, 0.84, 0.46)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['Mat_Frosted'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.028, depth=5.8, location=(0.0, 2.45, 2.05))
obj = bpy.context.active_object
obj.name = 'Pipe_Back_H1'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.019'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=4.0, location=(0.0, 2.45, 1.8))
obj = bpy.context.active_object
obj.name = 'Pipe_Back_H2'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.020'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.05, depth=5.0, location=(-1.0, 0.0, 2.3))
obj = bpy.context.active_object
obj.name = 'Pipe_Ceil_FB'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.024'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.045, depth=2.4, location=(2.9, -0.8, 1.2))
obj = bpy.context.active_object
obj.name = 'Pipe_Right_V1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.025'
obj.data.materials.append(bpy.data.materials['Mat_Pipe_Dark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.038, depth=2.4, location=(2.85, -0.8, 1.2))
obj = bpy.context.active_object
obj.name = 'Pipe_Right_V2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.026'
obj.data.materials.append(bpy.data.materials['Mat_Pipe_Dark'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=1.2, location=(-2.2, 2.45, 1.6))
obj = bpy.context.active_object
obj.name = 'Pipe_Vert_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.021'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=1.0, location=(-0.5, 2.45, 1.6))
obj = bpy.context.active_object
obj.name = 'Pipe_Vert_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.022'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.8, location=(-1.2, 2.45, 1.6))
obj = bpy.context.active_object
obj.name = 'Pipe_Vert_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.023'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Copper'])

bpy.ops.object.light_add(type='POINT', location=(-2.0, 2.0, 2.1))
obj = bpy.context.active_object
obj.name = 'Point_Light_Boiler'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 80.0
obj.data.shadow_soft_size = 0.0

bpy.ops.object.light_add(type='POINT', location=(1.5, 2.0, 2.1))
obj = bpy.context.active_object
obj.name = 'Point_Light_Shelves'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 60.0
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.76, 0.55, 0.75))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.9, 1.5)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.55, 0.04))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Board_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.9, 0.022)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.55, 0.5))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Board_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.9, 0.022)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.55, 1.0))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Board_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.9, 0.022)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.55, 1.45))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Board_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.9, 0.022)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.1, 0.75))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Side_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.025, 1.5)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 1.0, 0.75))
obj = bpy.context.active_object
obj.name = 'Shelf_White_1_Side_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.025, 1.5)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['Mat_Shelf_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.55, 1.0))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.022, 2.0)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 0.08))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Board_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.5, 0.022)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 0.55))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Board_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.5, 0.022)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 1.05))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Board_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.5, 0.022)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 1.55))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Board_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.5, 0.022)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 1.98))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Board_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.2, 0.5, 0.022)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, 2.3, 1.0))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Side_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.028, 0.5, 2.0)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.7, 2.3, 1.0))
obj = bpy.context.active_object
obj.name = 'Shelf_Wood_1_Side_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.028, 0.5, 2.0)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Mat_Wood_Med'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.82, -2.1, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Door_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.04, 2.06)
obj.data.name = 'Cube.086'
obj.data.materials.append(bpy.data.materials['Mat_Frosted'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.38, -2.1, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Door_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.04, 2.06)
obj.data.name = 'Cube.087'
obj.data.materials.append(bpy.data.materials['Mat_Frosted'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, -2.1, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 2.12)
obj.data.name = 'Cube.083'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.65, -2.1, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Frame_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 2.12)
obj.data.name = 'Cube.084'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, -2.1, 2.1))
obj = bpy.context.active_object
obj.name = 'Shower_1_Frame_T'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.16, 0.04, 0.04)
obj.data.name = 'Cube.085'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, -1.55, 0.07))
obj = bpy.context.active_object
obj.name = 'Shower_1_Tray'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.1, 1.1, 0.07)
obj.data.name = 'Cube.082'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.1, -1.0, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Wall_B'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 0.1, 2.1)
obj.data.name = 'Cube.081'
obj.data.materials.append(bpy.data.materials['Mat_Blue_Tile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.55, -1.55, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Wall_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.1, 2.1)
obj.data.name = 'Cube.079'
obj.data.materials.append(bpy.data.materials['Mat_Blue_Tile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.65, -1.55, 1.05))
obj = bpy.context.active_object
obj.name = 'Shower_1_Wall_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.1, 2.1)
obj.data.name = 'Cube.080'
obj.data.materials.append(bpy.data.materials['Mat_Blue_Tile'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.05, depth=0.26, location=(2.7, -1.7, 1.1))
obj = bpy.context.active_object
obj.name = 'Shower_Bottle_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['Mat_Red_Plastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.06, depth=0.28, location=(2.7, -1.9, 1.1))
obj = bpy.context.active_object
obj.name = 'Shower_Bottle_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.7, -1.8, 0.5))
obj = bpy.context.active_object
obj.name = 'Shower_Side_Table'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.42, 0.5)
obj.data.name = 'Cube.088'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.6, 2.3, 1.28))
obj = bpy.context.active_object
obj.name = 'SW1_Bag_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 0.22, 0.18)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['Mat_Green_Cloth'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.95, 2.3, 1.28))
obj = bpy.context.active_object
obj.name = 'SW1_Basket_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.18, 0.2, 0.18)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Mat_Basket'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.13, depth=0.26, location=(1.6, 2.3, 1.8))
obj = bpy.context.active_object
obj.name = 'SW1_Basket_2'
obj.rotation_euler = (-0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['Mat_Basket'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.0, 2.3, 0.28))
obj = bpy.context.active_object
obj.name = 'SW1_Box_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.3, 0.2, 0.18)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.9, 2.3, 0.26))
obj = bpy.context.active_object
obj.name = 'SW1_Box_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.18, 0.16)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.9, 2.3, 0.77))
obj = bpy.context.active_object
obj.name = 'SW1_Box_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.18, 0.18)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 2.3, 1.27))
obj = bpy.context.active_object
obj.name = 'SW1_Box_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.25, 0.2, 0.18)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.05, 2.3, 1.78))
obj = bpy.context.active_object
obj.name = 'SW1_Box_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.24, 0.2, 0.2)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.9, 2.3, 1.78))
obj = bpy.context.active_object
obj.name = 'SW1_Box_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.28, 0.18, 0.2)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.12, depth=0.24, location=(1.5, 2.3, 0.8))
obj = bpy.context.active_object
obj.name = 'SW1_Pot_1'
obj.rotation_euler = (-0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Mat_Orange_Pot'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 2.3, 0.21))
obj = bpy.context.active_object
obj.name = 'SW1_Shoes_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.22, 0.1)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Mat_Dark_Ins'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.05, 2.3, 0.77))
obj = bpy.context.active_object
obj.name = 'SW1_Teal_Bin'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.2, 0.2)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Mat_Teal_Plastic'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 2.575, 1.2))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 0.15, 2.4)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.5, 2.4, 1.2))
obj = bpy.context.active_object
obj.name = 'Wall_Div_Boiler'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 0.2, 2.4)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -2.575, 1.2))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (6.0, 0.15, 2.4)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.075, 0.0, 1.2))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 5.0, 2.4)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.075, 0.0, 1.2))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.15, 5.0, 2.4)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.3, depth=1.82, location=(-0.5, 2.3, 0.9))
obj = bpy.context.active_object
obj.name = 'WH_1_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=0.3, location=(-0.5, 2.3, 1.81))
obj = bpy.context.active_object
obj.name = 'WH_1_Cap_T'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere.003'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.35, depth=1.8, location=(-0.5, 2.3, 0.9))
obj = bpy.context.active_object
obj.name = 'WH_1_Insulation'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['Mat_Dark_Ins'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, 1.75, 0.47))
obj = bpy.context.active_object
obj.name = 'WM_1_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.58, 0.56, 0.47)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.16, depth=0.04, location=(-2.63, 1.75, 0.38))
obj = bpy.context.active_object
obj.name = 'WM_1_Door'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, 1.75, 0.84))
obj = bpy.context.active_object
obj.name = 'WM_1_Panel'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.58, 0.56, 0.09)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['Mat_Metal_Gray'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, 1.75, 1.08))
obj = bpy.context.active_object
obj.name = 'WM_1_Persil_Box'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.24, 0.18, 0.14)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['Mat_Cardboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.35, 1.75, 0.97))
obj = bpy.context.active_object
obj.name = 'WM_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.58, 0.56, 0.03)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.55, 0.12))
obj = bpy.context.active_object
obj.name = 'WSH_Basket_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.35, 0.07)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.7, 0.62))
obj = bpy.context.active_object
obj.name = 'WSH_Basket_Nat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.22, 0.09)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['Mat_Basket'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.78, 0.4, 0.62))
obj = bpy.context.active_object
obj.name = 'WSH_Basket_Red'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.25, 0.1)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['Mat_Red_Plastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.14, depth=0.28, location=(2.78, 0.55, 1.78))
obj = bpy.context.active_object
obj.name = 'WSH_Bucket'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Mat_Teal_Plastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.12, depth=0.24, location=(2.78, 0.4, 1.22))
obj = bpy.context.active_object
obj.name = 'WSH_Pot_Red'
obj.rotation_euler = (-0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['Mat_Red_Plastic'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.15, depth=0.3, location=(2.78, 0.7, 1.24))
obj = bpy.context.active_object
obj.name = 'WSH_Pot_White'
obj.rotation_euler = (-0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['Mat_White'])

