"""
Blender Scene: scene0081_02.blend
Objects: 293
Materials: 20
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.85, 0.87, 0.9, 1.0)
    _bg.inputs['Strength'].default_value = 0.6

# ============================================================
# Materials
# ============================================================
mat_Mat_Chrome = bpy.data.materials.new(name='Mat_Chrome')
mat_Mat_Chrome.use_nodes = True
_bsdf = mat_Mat_Chrome.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.78, 0.78, 0.78, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.15
_bsdf.inputs['Metallic'].default_value = 0.95

mat_Mat_DeskBase = bpy.data.materials.new(name='Mat_DeskBase')
mat_Mat_DeskBase.use_nodes = True
_bsdf = mat_Mat_DeskBase.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.18, 0.2, 0.27, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.45
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_DeskRecess = bpy.data.materials.new(name='Mat_DeskRecess')
mat_Mat_DeskRecess.use_nodes = True
_bsdf = mat_Mat_DeskRecess.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.28, 0.3, 0.35, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_DeskTop = bpy.data.materials.new(name='Mat_DeskTop')
mat_Mat_DeskTop.use_nodes = True
_bsdf = mat_Mat_DeskTop.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.91, 0.91, 0.89, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.25
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Floor = bpy.data.materials.new(name='Mat_Floor')
mat_Mat_Floor.use_nodes = True
_bsdf = mat_Mat_Floor.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.7, 0.64, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.85
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Glass = bpy.data.materials.new(name='Mat_Glass')
mat_Mat_Glass.use_nodes = True
_bsdf = mat_Mat_Glass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.72, 0.8, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.25
mat_Mat_Glass.blend_method = 'BLEND'

mat_Mat_Monitor = bpy.data.materials.new(name='Mat_Monitor')
mat_Mat_Monitor.use_nodes = True
_bsdf = mat_Mat_Monitor.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.06, 0.06, 0.06, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_OfficeChair = bpy.data.materials.new(name='Mat_OfficeChair')
mat_Mat_OfficeChair.use_nodes = True
_bsdf = mat_Mat_OfficeChair.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.75, 0.77, 0.78, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Pillar = bpy.data.materials.new(name='Mat_Pillar')
mat_Mat_Pillar.use_nodes = True
_bsdf = mat_Mat_Pillar.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.62, 0.58, 0.52, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Plant = bpy.data.materials.new(name='Mat_Plant')
mat_Mat_Plant.use_nodes = True
_bsdf = mat_Mat_Plant.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.13, 0.44, 0.11, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Pot = bpy.data.materials.new(name='Mat_Pot')
mat_Mat_Pot.use_nodes = True
_bsdf = mat_Mat_Pot.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.4, 0.25, 0.14, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_RailGlass = bpy.data.materials.new(name='Mat_RailGlass')
mat_Mat_RailGlass.use_nodes = True
_bsdf = mat_Mat_RailGlass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.8, 0.85, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.2
mat_Mat_RailGlass.blend_method = 'BLEND'

mat_Mat_RailMetal = bpy.data.materials.new(name='Mat_RailMetal')
mat_Mat_RailMetal.use_nodes = True
_bsdf = mat_Mat_RailMetal.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.55, 0.4, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.3

mat_Mat_RedSofa = bpy.data.materials.new(name='Mat_RedSofa')
mat_Mat_RedSofa.use_nodes = True
_bsdf = mat_Mat_RedSofa.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.07, 0.05, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Screen = bpy.data.materials.new(name='Mat_Screen')
mat_Mat_Screen.use_nodes = True
_bsdf = mat_Mat_Screen.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.01, 0.01, 0.03, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_TableTop = bpy.data.materials.new(name='Mat_TableTop')
mat_Mat_TableTop.use_nodes = True
_bsdf = mat_Mat_TableTop.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.88, 0.88, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.25
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Wall = bpy.data.materials.new(name='Mat_Wall')
mat_Mat_Wall.use_nodes = True
_bsdf = mat_Mat_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.91, 0.9, 0.87, 1.0)
_bsdf.inputs['Roughness'].default_value = 1.0
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_WinFrame = bpy.data.materials.new(name='Mat_WinFrame')
mat_Mat_WinFrame.use_nodes = True
_bsdf = mat_Mat_WinFrame.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.2, 0.1, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_WoodBar = bpy.data.materials.new(name='Mat_WoodBar')
mat_Mat_WoodBar.use_nodes = True
_bsdf = mat_Mat_WoodBar.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.68, 0.4, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_WoodChair = bpy.data.materials.new(name='Mat_WoodChair')
mat_Mat_WoodChair.use_nodes = True
_bsdf = mat_Mat_WoodChair.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.65, 0.32, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.55
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.object.light_add(type='AREA', location=(-3.187851, 4.891391, 0.308847))
obj = bpy.context.active_object
obj.name = 'Area_Fill'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 300.0
obj.data.size = 10.0

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.72, location=(-5.0, -0.3, 0.36))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Column'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.125'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.18, depth=0.05, location=(-0.560709, -3.9505, 0.03))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Foot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.131'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.13, depth=0.02, location=(-0.560709, -3.9505, 0.3))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Footring'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.126'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-0.680709, -3.9505, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Leg_3'
obj.rotation_euler = (0.20944, -0.0, 0.0)
obj.data.name = 'Cylinder.129'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-0.560709, -4.0705, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Leg_4'
obj.rotation_euler = (0.0, 0.20944, 0.0)
obj.data.name = 'Cylinder.130'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.2, depth=0.05, location=(-0.560709, -3.9505, 0.72))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_2_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.124'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.72, location=(-1.260709, -4.650501, 0.36))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Column'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.133'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.18, depth=0.05, location=(-1.260709, -4.650501, 0.03))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Foot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.139'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.13, depth=0.02, location=(-1.260709, -4.650501, 0.3))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Footring'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.134'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-1.140709, -4.650501, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Leg_1'
obj.rotation_euler = (-0.20944, 0.0, 0.0)
obj.data.name = 'Cylinder.135'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-1.260709, -4.5305, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Leg_2'
obj.rotation_euler = (-0.0, -0.20944, 0.0)
obj.data.name = 'Cylinder.136'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-1.380709, -4.650501, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Leg_3'
obj.rotation_euler = (0.20944, -0.0, 0.0)
obj.data.name = 'Cylinder.137'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.014, depth=0.6, location=(-1.260709, -4.770501, 0.28))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Leg_4'
obj.rotation_euler = (0.0, 0.20944, 0.0)
obj.data.name = 'Cylinder.138'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.2, depth=0.05, location=(-1.260709, -4.650501, 0.72))
obj = bpy.context.active_object
obj.name = 'Bar_Stool_1_3_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.132'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.038, depth=1.08, location=(-0.560709, -4.650501, 0.54))
obj = bpy.context.active_object
obj.name = 'Bar_Table_1_Column'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.111'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.24, depth=0.06, location=(-0.560709, -4.650501, 0.04))
obj = bpy.context.active_object
obj.name = 'Bar_Table_1_Foot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.112'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.46, depth=0.05, location=(-0.560709, -4.650501, 1.08))
obj = bpy.context.active_object
obj.name = 'Bar_Table_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.110'
obj.data.materials.append(bpy.data.materials['Mat_WoodBar'])

bpy.ops.object.camera_add(location=(0.308951, -7.378332, -1.341153))
obj = bpy.context.active_object
obj.name = 'Camera_Main'
obj.rotation_euler = (1.361357, 0.0, 0.0)
obj.data.lens = 24.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.488153, -5.680246, 0.8))
obj = bpy.context.active_object
obj.name = 'Chair_Office_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.07, 0.55)
obj.data.name = 'Cube.081'
obj.data.materials.append(bpy.data.materials['Mat_OfficeChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.35, depth=0.05, location=(-4.488153, -5.400246, 0.04))
obj = bpy.context.active_object
obj.name = 'Chair_Office_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.185'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.05, depth=0.5, location=(-4.488153, -5.400246, 0.26))
obj = bpy.context.active_object
obj.name = 'Chair_Office_Post'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.184'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.488153, -5.400246, 0.5))
obj = bpy.context.active_object
obj.name = 'Chair_Office_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.55, 0.55, 0.09)
obj.data.name = 'Cube.080'
obj.data.materials.append(bpy.data.materials['Mat_OfficeChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.488153, -5.000246, 0.07))
obj = bpy.context.active_object
obj.name = 'Chair_Office_SlA'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.48, 0.06, 0.06)
obj.data.name = 'Cube.082'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.488153, -5.800246, 0.07))
obj = bpy.context.active_object
obj.name = 'Chair_Office_SlB'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.48, 0.06, 0.06)
obj.data.name = 'Cube.083'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.488153, -5.400246, 0.07))
obj = bpy.context.active_object
obj.name = 'Chair_Office_SlF'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.8, 0.06)
obj.data.name = 'Cube.084'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=1.35, depth=0.85, location=(-4.5, -3.5, 0.43))
obj = bpy.context.active_object
obj.name = 'Desk_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.182'
obj.data.materials.append(bpy.data.materials['Mat_DeskBase'])

bpy.ops.object.light_add(type='POINT', location=(-4.5, -3.5, 2.5))
obj = bpy.context.active_object
obj.name = 'Desk_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 120.0
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.65, depth=0.05, location=(-4.5, -3.5, 0.89))
obj = bpy.context.active_object
obj.name = 'Desk_Recess'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.181'
obj.data.materials.append(bpy.data.materials['Mat_DeskRecess'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=1.5, depth=0.06, location=(-4.5, -3.5, 0.88))
obj = bpy.context.active_object
obj.name = 'Desk_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.180'
obj.data.materials.append(bpy.data.materials['Mat_DeskTop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.044187, 0.027271, -0.1))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 12.0, 0.2)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Mat_Floor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.97, -4.5, 1.6))
obj = bpy.context.active_object
obj.name = 'Glass_Left_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 2.0, 2.8)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Mat_RailGlass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.97, -2.0, 1.6))
obj = bpy.context.active_object
obj.name = 'Glass_Left_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 2.0, 2.8)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Mat_RailGlass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.97, 0.5, 1.6))
obj = bpy.context.active_object
obj.name = 'Glass_Left_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 2.0, 2.8)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Mat_RailGlass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.97, 3.0, 1.6))
obj = bpy.context.active_object
obj.name = 'Glass_Left_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 2.0, 2.8)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Mat_RailGlass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.5, -2.2, 1.22))
obj = bpy.context.active_object
obj.name = 'Monitor_Arm'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.08, 0.65)
obj.data.name = 'Cube.077'
obj.data.materials.append(bpy.data.materials['Mat_Monitor'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.08, location=(-4.5, -2.1, 1.38))
obj = bpy.context.active_object
obj.name = 'Monitor_Cam'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.183'
obj.data.materials.append(bpy.data.materials['Mat_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.5, -2.15, 1.68))
obj = bpy.context.active_object
obj.name = 'Monitor_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.1, 0.1, 0.65)
obj.data.name = 'Cube.078'
obj.data.materials.append(bpy.data.materials['Mat_Monitor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.5, -2.1, 1.68))
obj = bpy.context.active_object
obj.name = 'Monitor_Screen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.05, 0.04, 0.6)
obj.data.name = 'Cube.079'
obj.data.materials.append(bpy.data.materials['Mat_Screen'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.5, -0.5, 2.0))
obj = bpy.context.active_object
obj.name = 'Pillar_Stone'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.65, 0.65, 4.0)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Mat_Pillar'])

bpy.ops.mesh.primitive_uv_sphere_add(radius=1.275, location=(-5.5, 4.5, 2.0))
obj = bpy.context.active_object
obj.name = 'Plant_Leaves'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Sphere'
obj.data.materials.append(bpy.data.materials['Mat_Plant'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.64, location=(-5.5, 4.5, 0.32))
obj = bpy.context.active_object
obj.name = 'Plant_Pot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Mat_Pot'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.08, depth=0.5, location=(-5.5, 4.5, 0.9))
obj = bpy.context.active_object
obj.name = 'Plant_Trunk'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Mat_Pot'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.97, 0.0, 3.05))
obj = bpy.context.active_object
obj.name = 'Rail_Cap_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 12.0, 0.08)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['Mat_RailMetal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, 5.15, 0.52))
obj = bpy.context.active_object
obj.name = 'Red_Bench_A_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 0.14, 0.6)
obj.data.name = 'Cube.074'
obj.data.materials.append(bpy.data.materials['Mat_RedSofa'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.0, 4.8, 0.22))
obj = bpy.context.active_object
obj.name = 'Red_Bench_A_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 0.72, 0.44)
obj.data.name = 'Cube.073'
obj.data.materials.append(bpy.data.materials['Mat_RedSofa'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.88, 4.2, 0.52))
obj = bpy.context.active_object
obj.name = 'Red_Bench_B_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.14, 1.5, 0.6)
obj.data.name = 'Cube.076'
obj.data.materials.append(bpy.data.materials['Mat_RedSofa'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.5, 4.2, 0.22))
obj = bpy.context.active_object
obj.name = 'Red_Bench_B_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.72, 1.5, 0.44)
obj.data.name = 'Cube.075'
obj.data.materials.append(bpy.data.materials['Mat_RedSofa'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(-3.5, 2.5, 0.04))
obj = bpy.context.active_object
obj.name = 'Table_1_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.62, 2.5, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.66, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.98, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.66, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.98, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.82, 2.5, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_E_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 3.38, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 3.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 3.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 3.02, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 3.02, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 3.18, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_N_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 1.62, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 1.98, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 1.98, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 1.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 1.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 1.82, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_S_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.38, 2.5, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.02, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.34, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.02, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.34, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.019'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.18, 2.5, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_1_Chair_W_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(-3.5, 2.5, 0.38))
obj = bpy.context.active_object
obj.name = 'Table_1_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 2.5, 0.76))
obj = bpy.context.active_object
obj.name = 'Table_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(0.106491, 2.75102, 0.012022))
obj = bpy.context.active_object
obj.name = 'Table_2_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.021'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(0.870296, -0.796009, -0.243552))
obj = bpy.context.active_object
obj.name = 'Table_2_Base.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.207'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(0.171178, 1.834523, -0.002069))
obj = bpy.context.active_object
obj.name = 'Table_2_Base.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.217'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(0.06496, 0.920947, 0.02653))
obj = bpy.context.active_object
obj.name = 'Table_2_Base.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.219'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.88, 2.5, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.750296, -0.796009, 0.456448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Back.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.092'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.84, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.030'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.710296, -0.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_1.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.198'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.52, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.031'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.390296, -0.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_2.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.199'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.84, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.032'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.710296, -0.956009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_3.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.200'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.52, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.033'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.390296, -0.956009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Leg_4.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.201'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.68, 2.5, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.550296, -0.796009, 0.176448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_E_Seat.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.091'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 3.38, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.870296, 0.083991, 0.456448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Back.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.088'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.16, 3.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.022'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.030296, 0.043991, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_1.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.190'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.16, 3.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.023'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.710296, 0.043991, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_2.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.191'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.16, 3.02, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.024'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.030296, -0.276009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_3.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.192'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.16, 3.02, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.025'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.710296, -0.276009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Leg_4.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.193'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 3.18, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.870296, -0.116009, 0.176448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_N_Seat.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.087'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.782111, 1.62, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.870296, -1.676009, 0.456448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Back.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.090'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.622111, 1.98, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.026'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.030296, -1.316009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_1.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.194'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.942111, 1.98, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.027'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.710296, -1.316009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_2.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.195'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.622111, 1.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.028'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.030296, -1.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_3.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.196'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.942111, 1.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.029'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.710296, -1.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Leg_4.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.197'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.782111, 1.82, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.870296, -1.476009, 0.176448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_S_Seat.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.089'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.88, 2.5, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.009704, -0.796009, 0.456448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Back.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.094'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.52, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.034'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.350296, -0.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_1.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.202'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.84, 2.66, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.035'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.030296, -0.636009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_2.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.203'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.52, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.036'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.350296, -0.956009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_3.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.204'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.84, 2.34, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.037'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.030296, -0.956009, -0.043552))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Leg_4.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.205'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.68, 2.5, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.190296, -0.796009, 0.176448))
obj = bpy.context.active_object
obj.name = 'Table_2_Chair_W_Seat.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.093'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(0.106491, 2.75102, 0.352022))
obj = bpy.context.active_object
obj.name = 'Table_2_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.020'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(0.870296, -0.796009, 0.096448))
obj = bpy.context.active_object
obj.name = 'Table_2_Pedestal.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.206'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(0.171178, 1.834523, 0.337931))
obj = bpy.context.active_object
obj.name = 'Table_2_Pedestal.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.216'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(0.06496, 0.920947, 0.36653))
obj = bpy.context.active_object
obj.name = 'Table_2_Pedestal.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.218'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.106491, 2.75102, 0.732022))
obj = bpy.context.active_object
obj.name = 'Table_2_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.870296, -0.796009, 0.476448))
obj = bpy.context.active_object
obj.name = 'Table_2_Top.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.095'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.171178, 1.834523, 0.717931))
obj = bpy.context.active_object
obj.name = 'Table_2_Top.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.100'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.06496, 0.920947, 0.74653))
obj = bpy.context.active_object
obj.name = 'Table_2_Top.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.101'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(-3.5, 0.0, 0.04))
obj = bpy.context.active_object
obj.name = 'Table_4_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.057'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.62, 0.0, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.303754, -2.961475, 0.640596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.086'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-16.605886, -85.310379, -41.044792))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.097'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.872576, 0.01196, 0.416859))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.099'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.627764, 1.030152, 0.600081))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.103'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.628542, 0.522335, 0.616339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.105'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.610647, -2.389421, 0.44254))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.107'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.064551, 1.162935, 0.647053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.109'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.140391, 0.63459, 0.646589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.111'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.920749, 1.813486, 0.718871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.113'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.772044, -0.431622, 0.682778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.115'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.962908, -2.039904, 0.559844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Back.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.117'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.66, 0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.066'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-6.343754, -2.801475, 0.140596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.186'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-16.645885, -85.150383, -41.544792))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.208'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.832577, 0.17196, -0.083141))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.212'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.667764, 1.190153, 0.100081))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.220'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.668542, 0.682335, 0.116339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.224'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.570647, -2.229421, -0.05746))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.228'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.024551, 1.322936, 0.147053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.232'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.100391, 0.79459, 0.146589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.236'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.880749, 1.973486, 0.218871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.240'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.812044, -0.271621, 0.182778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.244'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.922908, -1.879903, 0.059844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_1.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.248'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.98, 0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.067'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-6.663754, -2.801475, 0.140596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.187'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-16.965885, -85.150383, -41.544792))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.209'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.512576, 0.17196, -0.083141))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.213'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.987765, 1.190153, 0.100081))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.221'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.988542, 0.682335, 0.116339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.225'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.150304, 0.754053, -0.287711))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.229'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.704551, 1.322936, 0.147053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.233'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.780391, 0.79459, 0.146589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.237'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.560749, 1.973486, 0.218871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.241'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-1.132044, -0.271621, 0.182778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.245'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.602908, -1.879903, 0.059844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_2.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.249'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.66, -0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.068'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-6.343754, -3.121475, 0.140596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.188'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-16.645885, -85.470383, -41.544792))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.210'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.832577, -0.14804, -0.083141))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.214'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.234069, -2.190277, -0.0542))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.222'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.668542, 0.362335, 0.116339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.226'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.570647, -2.549421, -0.05746))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.230'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.024551, 1.002936, 0.147053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.234'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.100391, 0.47459, 0.146589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.238'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.880749, 1.653486, 0.218871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.242'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.812044, -0.591622, 0.182778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.246'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.922908, -2.199903, 0.059844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_3.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.250'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.98, -0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.069'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-6.663754, -3.121475, 0.140596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.189'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-16.965885, -85.470383, -41.544792))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.211'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.512576, -0.14804, -0.083141))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.215'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.987765, 0.870152, 0.100081))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.223'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-0.988542, 0.362335, 0.116339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.227'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.150304, 0.434053, -0.287711))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.231'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.704551, 1.002936, 0.147053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.235'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.780391, 0.47459, 0.146589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.239'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.560749, 1.653486, 0.218871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.243'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-1.132044, -0.591622, 0.182778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.247'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.602908, -2.199903, 0.059844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Leg_4.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.251'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.82, 0.0, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.503754, -2.961475, 0.360596))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.001'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.085'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-16.805885, -85.310379, -41.324791))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.002'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.096'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.672577, 0.01196, 0.136859))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.003'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.098'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.827764, 1.030152, 0.320081))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.004'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.102'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.828542, 0.522335, 0.336339))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.005'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.104'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.410647, -2.389421, 0.16254))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.006'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.106'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.864552, 1.162935, 0.367053))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.007'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.108'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.940391, 0.63459, 0.366589))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.008'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.110'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.720749, 1.813486, 0.438871))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.009'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.112'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.972043, -0.431622, 0.402778))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.010'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.114'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.762908, -2.039904, 0.279844))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_E_Seat.011'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.116'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 0.88, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 0.84, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.058'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 0.84, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.059'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, 0.52, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.060'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, 0.52, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.061'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 0.68, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_N_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, -0.88, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, -0.52, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.062'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, -0.52, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.063'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.34, -0.84, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.064'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.66, -0.84, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.065'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, -0.68, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_S_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.38, 0.0, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.02, 0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.070'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.34, 0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.071'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.02, -0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.072'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.34, -0.16, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.073'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.18, 0.0, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_4_Chair_W_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(-3.5, 0.0, 0.38))
obj = bpy.context.active_object
obj.name = 'Table_4_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.056'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.5, 0.0, 0.76))
obj = bpy.context.active_object
obj.name = 'Table_4_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(-3.496802, 4.769723, 0.04))
obj = bpy.context.active_object
obj.name = 'Table_5_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.075'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.616802, 4.769723, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.656802, 4.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.084'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.976802, 4.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.085'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.656802, 4.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.086'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-2.976802, 4.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.087'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.816802, 4.769723, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_E_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.496802, 5.649723, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.336802, 5.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.076'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.656802, 5.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.077'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.336802, 5.289723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.078'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.656802, 5.289723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.079'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.496802, 5.449723, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_N_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.496802, 3.889723, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.336802, 4.249723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.080'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.656802, 4.249723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.081'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.336802, 3.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.082'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-3.656802, 3.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.083'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.496802, 4.089723, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_S_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.376802, 4.769723, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.016802, 4.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.088'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.336802, 4.929723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.089'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.016802, 4.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.090'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(-4.336802, 4.609723, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.091'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.176802, 4.769723, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_5_Chair_W_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(-3.496802, 4.769723, 0.38))
obj = bpy.context.active_object
obj.name = 'Table_5_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.074'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.496802, 4.769723, 0.76))
obj = bpy.context.active_object
obj.name = 'Table_5_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.28, depth=0.06, location=(0.862298, -2.951779, 0.04))
obj = bpy.context.active_object
obj.name = 'Table_6_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.093'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.742298, -2.951779, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.070'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.702298, -2.791779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.102'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.382298, -2.791779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.103'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.702298, -3.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.104'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.382298, -3.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.105'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.542298, -2.951779, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_E_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.069'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.862298, -2.071779, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.022298, -2.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.094'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.702298, -2.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.095'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.022298, -2.431779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.096'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.702298, -2.431779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.097'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.862298, -2.271779, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_N_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.862298, -3.831779, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.42, 0.07, 0.36)
obj.data.name = 'Cube.068'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.022298, -3.471779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.098'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.702298, -3.471779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.099'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(1.022298, -3.791779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.100'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.702298, -3.791779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.101'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.862298, -3.631779, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_S_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.067'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.017702, -2.951779, 0.74))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.42, 0.36)
obj.data.name = 'Cube.072'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.342298, -2.791779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Leg_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.106'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.280158, -2.605498, 0.009748))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Leg_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.107'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.342298, -3.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Leg_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.108'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=0.44, location=(0.022298, -3.111779, 0.24))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Leg_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.109'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.182298, -2.951779, 0.46))
obj = bpy.context.active_object
obj.name = 'Table_6_Chair_W_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.07)
obj.data.name = 'Cube.071'
obj.data.materials.append(bpy.data.materials['Mat_WoodChair'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.048, depth=0.76, location=(0.862298, -2.951779, 0.38))
obj = bpy.context.active_object
obj.name = 'Table_6_Pedestal'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.092'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.862298, -2.951779, 0.76))
obj = bpy.context.active_object
obj.name = 'Table_6_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.92, 0.06)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['Mat_TableTop'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 6.0, 2.0))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.2, 4.0)
obj.data.name = 'Cube.001'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -6.0, 2.0))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.2, 4.0)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-7.0, 0.0, 2.0))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 12.0, 4.0)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(7.0, 0.0, 2.0))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 12.0, 4.0)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Mat_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 5.95, 0.9))
obj = bpy.context.active_object
obj.name = 'Wall_Wood_Panel'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.06, 1.8)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Mat_WinFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'Window_Back_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.8, 0.06, 2.0)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Mat_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'Window_Back_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.8, 0.06, 2.0)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Mat_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'Window_Back_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.8, 0.06, 2.0)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Mat_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-4.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'WinFrame_Back_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.95, 0.1, 2.15)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Mat_WinFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'WinFrame_Back_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.95, 0.1, 2.15)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Mat_WinFrame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.0, 5.97, 2.4))
obj = bpy.context.active_object
obj.name = 'WinFrame_Back_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.95, 0.1, 2.15)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['Mat_WinFrame'])

