"""
Blender Scene: scene0702_01.blend
Objects: 36
Materials: 12
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.8, 0.78, 0.74, 1.0)
    _bg.inputs['Strength'].default_value = 1.0

# ============================================================
# Materials
# ============================================================
mat_Mat_Bag = bpy.data.materials.new(name='Mat_Bag')
mat_Mat_Bag.use_nodes = True
_bsdf = mat_Mat_Bag.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.6, 0.58, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.85
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.8
mat_Mat_Bag.blend_method = 'BLEND'

mat_Mat_Ceiling = bpy.data.materials.new(name='Mat_Ceiling')
mat_Mat_Ceiling.use_nodes = True
_bsdf = mat_Mat_Ceiling.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.94, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.55
mat_Mat_Ceiling.blend_method = 'BLEND'

mat_Mat_Chrome = bpy.data.materials.new(name='Mat_Chrome')
mat_Mat_Chrome.use_nodes = True
_bsdf = mat_Mat_Chrome.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.75, 0.75, 0.75, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.2
_bsdf.inputs['Metallic'].default_value = 0.95

mat_Mat_Curtain = bpy.data.materials.new(name='Mat_Curtain')
mat_Mat_Curtain.use_nodes = True
_bsdf = mat_Mat_Curtain.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.96, 0.96, 0.94, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.85
mat_Mat_Curtain.blend_method = 'BLEND'

mat_Mat_FloorTile = bpy.data.materials.new(name='Mat_FloorTile')
mat_Mat_FloorTile.use_nodes = True
_bsdf = mat_Mat_FloorTile.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.88, 0.87, 0.84, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_TileWhite = bpy.data.materials.new(name='Mat_TileWhite')
mat_Mat_TileWhite.use_nodes = True
_bsdf = mat_Mat_TileWhite.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.91, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.35
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_TP = bpy.data.materials.new(name='Mat_TP')
mat_Mat_TP.use_nodes = True
_bsdf = mat_Mat_TP.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.93, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_Trash = bpy.data.materials.new(name='Mat_Trash')
mat_Mat_Trash.use_nodes = True
_bsdf = mat_Mat_Trash.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.4, 0.4, 0.38, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_TubInside = bpy.data.materials.new(name='Mat_TubInside')
mat_Mat_TubInside.use_nodes = True
_bsdf = mat_Mat_TubInside.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.75, 0.75, 0.73, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_WallUpper = bpy.data.materials.new(name='Mat_WallUpper')
mat_Mat_WallUpper.use_nodes = True
_bsdf = mat_Mat_WallUpper.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.78, 0.74, 0.68, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_White = bpy.data.materials.new(name='Mat_White')
mat_Mat_White.use_nodes = True
_bsdf = mat_Mat_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.93, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.55
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mat_WoodDoor = bpy.data.materials.new(name='Mat_WoodDoor')
mat_Mat_WoodDoor.use_nodes = True
_bsdf = mat_Mat_WoodDoor.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.4, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.65
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.object.light_add(type='POINT', location=(-0.6, 0.5, 1.8))
obj = bpy.context.active_object
obj.name = 'Back_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 80.0
obj.data.shadow_soft_size = 0.0

bpy.ops.object.camera_add(location=(0.1, -1.0, 1.35))
obj = bpy.context.active_object
obj.name = 'Camera'
obj.rotation_euler = (1.396263, 0.0, 0.087266)
obj.data.lens = 18.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.object.light_add(type='AREA', location=(0.0, 0.0, 2.44))
obj = bpy.context.active_object
obj.name = 'Ceiling_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 500.0
obj.data.size = 0.8

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.018, depth=1.18, location=(-0.68, 0.4, 2.1))
obj = bpy.context.active_object
obj.name = 'Curtain_Rod'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.82, -1.42, 1.05))
obj = bpy.context.active_object
obj.name = 'Door_Panel'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.86, 0.04, 2.1)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Mat_WoodDoor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.32, -1.34, 1.05))
obj = bpy.context.active_object
obj.name = 'DoorFrame_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.24, 2.1)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Mat_WoodDoor'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, -1.34, 2.12))
obj = bpy.context.active_object
obj.name = 'DoorFrame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.9, 0.24, 0.06)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['Mat_WoodDoor'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.035, depth=0.1, location=(-1.18, 0.68, 1.12))
obj = bpy.context.active_object
obj.name = 'Faucet_Knob_C'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.035, depth=0.1, location=(-1.18, 0.38, 1.12))
obj = bpy.context.active_object
obj.name = 'Faucet_Knob_H'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.object.light_add(type='POINT', location=(0.2, -0.5, 1.8))
obj = bpy.context.active_object
obj.name = 'Fill_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 100.0
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.04))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.4, 2.6, 0.08)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Mat_FloorTile'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.4, 1.24, 0.88))
obj = bpy.context.active_object
obj.name = 'Grab_Bar'
obj.rotation_euler = (0.0, 0.488692, 0.0)
obj.scale = (0.07, 0.05, 0.52)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.68, 0.26, 1.3))
obj = bpy.context.active_object
obj.name = 'Shower_Curtain'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.0, 0.04, 1.58)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Mat_Curtain'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.055, depth=0.11, location=(-1.12, 0.55, 1.8))
obj = bpy.context.active_object
obj.name = 'Shower_Head'
obj.rotation_euler = (-0.0, 2.879793, -0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.025, depth=0.4, location=(-1.18, 0.55, 1.55))
obj = bpy.context.active_object
obj.name = 'Shower_Pipe'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.3, 0.92, 0.22))
obj = bpy.context.active_object
obj.name = 'Toilet_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.38, 0.52, 0.44)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.3, 1.06, 0.66))
obj = bpy.context.active_object
obj.name = 'Toilet_Lid'
obj.rotation_euler = (-0.436332, 0.0, 0.0)
obj.scale = (0.34, 0.04, 0.36)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.3, 0.94, 0.48))
obj = bpy.context.active_object
obj.name = 'Toilet_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.34, 0.46, 0.04)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.3, 1.16, 0.6))
obj = bpy.context.active_object
obj.name = 'Toilet_Tank'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.38, 0.18, 0.44)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.88, 1.26, 0.9))
obj = bpy.context.active_object
obj.name = 'TP_Housing'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.18, 0.06, 0.3)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Mat_Chrome'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.055, depth=0.11, location=(-1.0, 0.05, 0.06))
obj = bpy.context.active_object
obj.name = 'TP_Roll_Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Mat_TP'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.055, depth=0.14, location=(0.88, 1.23, 0.82))
obj = bpy.context.active_object
obj.name = 'TP_Roll_Lower'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['Mat_TP'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.055, depth=0.14, location=(0.88, 1.23, 1.0))
obj = bpy.context.active_object
obj.name = 'TP_Roll_Upper'
obj.rotation_euler = (1.570796, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Mat_TP'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.72, 1.02, 0.37))
obj = bpy.context.active_object
obj.name = 'TrashBag'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.24, 0.24, 0.06)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Mat_Bag'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.72, 1.02, 0.18))
obj = bpy.context.active_object
obj.name = 'TrashCan_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.22, 0.22, 0.34)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Mat_Trash'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.68, 0.62, 0.22))
obj = bpy.context.active_object
obj.name = 'Tub_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.04, 1.18, 0.44)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.68, 0.62, 0.36))
obj = bpy.context.active_object
obj.name = 'Tub_Inner'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 1.06, 0.22)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Mat_TubInside'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.68, 0.62, 0.44))
obj = bpy.context.active_object
obj.name = 'Tub_Rim'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.04, 1.18, 0.03)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Mat_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 1.34, 1.85))
obj = bpy.context.active_object
obj.name = 'Wall_Back_Hi'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.4, 0.08, 1.3)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Mat_WallUpper'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 1.34, 0.6))
obj = bpy.context.active_object
obj.name = 'Wall_Back_Lo'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (2.4, 0.08, 1.2)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Mat_TileWhite'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.55, -1.34, 1.25))
obj = bpy.context.active_object
obj.name = 'Wall_Front_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.3, 0.08, 2.5)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Mat_WallUpper'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.8, -1.34, 2.15))
obj = bpy.context.active_object
obj.name = 'Wall_Front_TopR'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.8, 0.08, 0.7)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Mat_WallUpper'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.24, 0.0, 1.85))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Hi'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 2.6, 1.3)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['Mat_WallUpper'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.24, 0.0, 0.6))
obj = bpy.context.active_object
obj.name = 'Wall_Left_Lo'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 2.6, 1.2)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Mat_TileWhite'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.24, 0.0, 1.85))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Hi'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 2.6, 1.3)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Mat_WallUpper'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.24, 0.0, 0.6))
obj = bpy.context.active_object
obj.name = 'Wall_Right_Lo'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 2.6, 1.2)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Mat_TileWhite'])

