"""
Blender Scene: scene0187_01.blend
Objects: 96
Materials: 26
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.82, 0.85, 0.88, 1.0)
    _bg.inputs['Strength'].default_value = 0.6

# ============================================================
# Materials
# ============================================================
mat_Baseboard = bpy.data.materials.new(name='Baseboard')
mat_Baseboard.use_nodes = True
_bsdf = mat_Baseboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.06, 0.06, 0.07, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Beige_Fabric = bpy.data.materials.new(name='Beige_Fabric')
mat_Beige_Fabric.use_nodes = True
_bsdf = mat_Beige_Fabric.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.82, 0.76, 0.58, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.92
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Black_Chair = bpy.data.materials.new(name='Black_Chair')
mat_Black_Chair.use_nodes = True
_bsdf = mat_Black_Chair.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.07, 0.07, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.55
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Blue_Bin = bpy.data.materials.new(name='Blue_Bin')
mat_Blue_Bin.use_nodes = True
_bsdf = mat_Blue_Bin.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.14, 0.24, 0.68, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.6
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Blue_Curtain = bpy.data.materials.new(name='Blue_Curtain')
mat_Blue_Curtain.use_nodes = True
_bsdf = mat_Blue_Curtain.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.16, 0.28, 0.62, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.88
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Brown_Fabric = bpy.data.materials.new(name='Brown_Fabric')
mat_Brown_Fabric.use_nodes = True
_bsdf = mat_Brown_Fabric.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.42, 0.32, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.88
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Carpet = bpy.data.materials.new(name='Carpet')
mat_Carpet.use_nodes = True
_bsdf = mat_Carpet.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.22, 0.24, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.95
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Ceiling = bpy.data.materials.new(name='Ceiling')
mat_Ceiling.use_nodes = True
_bsdf = mat_Ceiling.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.96, 0.96, 0.96, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.12
mat_Ceiling.blend_method = 'BLEND'

mat_Dark_Bag = bpy.data.materials.new(name='Dark_Bag')
mat_Dark_Bag.use_nodes = True
_bsdf = mat_Dark_Bag.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.14, 0.11, 0.09, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.82
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Dark_Base = bpy.data.materials.new(name='Dark_Base')
mat_Dark_Base.use_nodes = True
_bsdf = mat_Dark_Base.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.16, 0.13, 0.1, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.45
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Dark_Panel = bpy.data.materials.new(name='Dark_Panel')
mat_Dark_Panel.use_nodes = True
_bsdf = mat_Dark_Panel.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.18, 0.18, 0.19, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.58
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Dark_Top = bpy.data.materials.new(name='Dark_Top')
mat_Dark_Top.use_nodes = True
_bsdf = mat_Dark_Top.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.18, 0.15, 0.12, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.28
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Green_Bin = bpy.data.materials.new(name='Green_Bin')
mat_Green_Bin.use_nodes = True
_bsdf = mat_Green_Bin.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.44, 0.14, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.62
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Lime_Green = bpy.data.materials.new(name='Lime_Green')
mat_Lime_Green.use_nodes = True
_bsdf = mat_Lime_Green.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.3, 0.78, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.68
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Orange_Stool = bpy.data.materials.new(name='Orange_Stool')
mat_Orange_Stool.use_nodes = True
_bsdf = mat_Orange_Stool.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.88, 0.38, 0.06, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Orange_Wall = bpy.data.materials.new(name='Orange_Wall')
mat_Orange_Wall.use_nodes = True
_bsdf = mat_Orange_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.82, 0.3, 0.08, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.72
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Red_Orange = bpy.data.materials.new(name='Red_Orange')
mat_Red_Orange.use_nodes = True
_bsdf = mat_Red_Orange.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.82, 0.22, 0.06, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.72
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Silver_Metal = bpy.data.materials.new(name='Silver_Metal')
mat_Silver_Metal.use_nodes = True
_bsdf = mat_Silver_Metal.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.72, 0.72, 0.74, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.18
_bsdf.inputs['Metallic'].default_value = 0.92

mat_Table_Base = bpy.data.materials.new(name='Table_Base')
mat_Table_Base.use_nodes = True
_bsdf = mat_Table_Base.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.55, 0.58, 0.62, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.32
_bsdf.inputs['Metallic'].default_value = 0.65

mat_TV_Screen = bpy.data.materials.new(name='TV_Screen')
mat_TV_Screen.use_nodes = True
_bsdf = mat_TV_Screen.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.04, 0.04, 0.05, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.18
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wall = bpy.data.materials.new(name='Wall')
mat_Wall.use_nodes = True
_bsdf = mat_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_White_Body = bpy.data.materials.new(name='White_Body')
mat_White_Body.use_nodes = True
_bsdf = mat_White_Body.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.32
_bsdf.inputs['Metallic'].default_value = 0.0

mat_White_Cabinet = bpy.data.materials.new(name='White_Cabinet')
mat_White_Cabinet.use_nodes = True
_bsdf = mat_White_Cabinet.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.91, 0.91, 0.89, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.35
_bsdf.inputs['Metallic'].default_value = 0.0

mat_White_Top = bpy.data.materials.new(name='White_Top')
mat_White_Top.use_nodes = True
_bsdf = mat_White_Top.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.9, 0.88, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.38
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wood_Door = bpy.data.materials.new(name='Wood_Door')
mat_Wood_Door.use_nodes = True
_bsdf = mat_Wood_Door.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.52, 0.36, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.55
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wood_Seat = bpy.data.materials.new(name='Wood_Seat')
mat_Wood_Seat.use_nodes = True
_bsdf = mat_Wood_Seat.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.4, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.object.light_add(type='AREA', location=(-3.5, -2.5, 2.85))
obj = bpy.context.active_object
obj.name = 'Area_Light_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 250.0
obj.data.color = (1.0, 0.97, 0.95)
obj.data.size = 2.5

bpy.ops.object.light_add(type='AREA', location=(3.5, -2.5, 2.85))
obj = bpy.context.active_object
obj.name = 'Area_Light_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 250.0
obj.data.color = (1.0, 0.97, 0.95)
obj.data.size = 2.5

bpy.ops.object.light_add(type='AREA', location=(-3.5, 2.5, 2.85))
obj = bpy.context.active_object
obj.name = 'Area_Light_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 250.0
obj.data.color = (1.0, 0.97, 0.95)
obj.data.size = 2.5

bpy.ops.object.light_add(type='AREA', location=(3.5, 2.5, 2.85))
obj = bpy.context.active_object
obj.name = 'Area_Light_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 250.0
obj.data.color = (1.0, 0.97, 0.95)
obj.data.size = 2.5

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, -1.0, 0.22))
obj = bpy.context.active_object
obj.name = 'Backpack_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.36, 0.26, 0.56)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['Dark_Bag'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.5, -1.0, 0.5))
obj = bpy.context.active_object
obj.name = 'Backpack_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.32, 0.22, 0.12)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['Dark_Bag'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 5.96, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.08, 0.12)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -5.96, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.08, 0.12)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.96, 0.0, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 12.0, 0.12)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(6.96, 0.0, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 12.0, 0.12)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.6, -0.3, 0.74))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.06, 0.44)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['Black_Chair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.78, -0.68, 0.25))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Leg_-0.18_-0.18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.5)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['Black_Chair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.78, -0.32, 0.25))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Leg_-0.18_0.18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.5)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['Black_Chair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.42, -0.68, 0.25))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Leg_0.18_-0.18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.5)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['Black_Chair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.42, -0.32, 0.25))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Leg_0.18_0.18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.04, 0.5)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['Black_Chair'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.6, -0.5, 0.49))
obj = bpy.context.active_object
obj.name = 'Black_Chair_1_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.44, 0.08)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['Wood_Seat'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.2, depth=0.76, location=(4.8, 5.4, 0.38))
obj = bpy.context.active_object
obj.name = 'Blue_Bin'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.021'
obj.data.materials.append(bpy.data.materials['Blue_Bin'])

bpy.ops.object.camera_add(location=(0.0, -9.0, 3.8))
obj = bpy.context.active_object
obj.name = 'Camera_Main'
obj.rotation_euler = (1.082104, 0.0, 0.0)
obj.data.lens = 26.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.2, 2.8, 0.2))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.8, 0.4)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['White_Body'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.6, 2.48, 0.04))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Leg_-1_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.08)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.6, 3.12, 0.04))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Leg_-1_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.08)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 2.48, 0.04))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Leg_1_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.08)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.8, 3.12, 0.04))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Leg_1_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.08)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(3.2, 2.8, 0.42))
obj = bpy.context.active_object
obj.name = 'Coffee_Table_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.8, 0.04)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Dark_Top'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.92, -1.0, 1.8))
obj = bpy.context.active_object
obj.name = 'Curtain_Left_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 4.0, 2.4)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Blue_Curtain'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-6.92, 2.5, 1.8))
obj = bpy.context.active_object
obj.name = 'Curtain_Left_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.16, 2.4, 2.4)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Blue_Curtain'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 6.0, 1.05))
obj = bpy.context.active_object
obj.name = 'Door'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.0, 0.12, 2.1)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Wood_Door'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.5, 6.0, 1.1))
obj = bpy.context.active_object
obj.name = 'Door_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.1, 0.08, 2.2)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.object.light_add(type='POINT', location=(0.0, 0.0, 2.6))
obj = bpy.context.active_object
obj.name = 'Fill_Light'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 120.0
obj.data.color = (0.95, 0.97, 1.0)
obj.data.shadow_soft_size = 0.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.05))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 12.0, 0.1)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Carpet'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.17, depth=0.56, location=(4.1, 5.4, 0.28))
obj = bpy.context.active_object
obj.name = 'Green_Bin'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.022'
obj.data.materials.append(bpy.data.materials['Green_Bin'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.2, depth=0.06, location=(1.2, 0.3, 0.06))
obj = bpy.context.active_object
obj.name = 'Green_Stool_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.016'
obj.data.materials.append(bpy.data.materials['Lime_Green'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.1, depth=0.18, location=(1.2, 0.3, 0.26))
obj = bpy.context.active_object
obj.name = 'Green_Stool_Mid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.015'
obj.data.materials.append(bpy.data.materials['Lime_Green'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.2, depth=0.1, location=(1.2, 0.3, 0.44))
obj = bpy.context.active_object
obj.name = 'Green_Stool_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.014'
obj.data.materials.append(bpy.data.materials['Lime_Green'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.6, 4.88, 0.54))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.76, 0.12, 0.68)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.6, 4.5, 0.06))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.8, 0.84, 0.12)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Dark_Base'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(4.3, 4.16, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Leg_-0_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(4.3, 4.84, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Leg_-0_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.002'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(4.9, 4.16, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Leg_0_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.001'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(4.9, 4.84, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Leg_0_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.003'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.6, 4.45, 0.3))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.64, 0.7, 0.24)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Beige_Fabric'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.22, 4.5, 0.36))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Side_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.8, 0.48)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(4.98, 4.5, 0.36))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_1_Side_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.8, 0.48)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.7, 4.88, 0.54))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.76, 0.12, 0.68)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.7, 4.5, 0.06))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.8, 0.84, 0.12)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Dark_Base'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(5.4, 4.16, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Leg_-0_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.004'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(5.4, 4.84, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Leg_-0_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.006'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(6.0, 4.16, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Leg_0_-0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.005'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.022, depth=0.1, location=(6.0, 4.84, 0.05))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Leg_0_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.007'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.7, 4.45, 0.3))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.64, 0.7, 0.24)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['Beige_Fabric'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.32, 4.5, 0.36))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Side_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.8, 0.48)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(6.08, 4.5, 0.36))
obj = bpy.context.active_object
obj.name = 'Lounge_Chair_2_Side_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.8, 0.48)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['Dark_Panel'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.22, depth=0.06, location=(3.0, -1.8, 0.06))
obj = bpy.context.active_object
obj.name = 'Orange_Stool_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.019'
obj.data.materials.append(bpy.data.materials['Orange_Stool'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.11, depth=0.18, location=(3.0, -1.8, 0.26))
obj = bpy.context.active_object
obj.name = 'Orange_Stool_Mid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.018'
obj.data.materials.append(bpy.data.materials['Orange_Stool'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.22, depth=0.1, location=(3.0, -1.8, 0.44))
obj = bpy.context.active_object
obj.name = 'Orange_Stool_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.017'
obj.data.materials.append(bpy.data.materials['Orange_Stool'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.4, 2.2, 0.04))
obj = bpy.context.active_object
obj.name = 'Ottoman_Arm_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.4, 0.05, 0.05)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.261803, 2.390211, 0.04))
obj = bpy.context.active_object
obj.name = 'Ottoman_Arm_1'
obj.rotation_euler = (0.0, 0.0, 1.256637)
obj.scale = (0.4, 0.05, 0.05)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.038197, 2.317557, 0.04))
obj = bpy.context.active_object
obj.name = 'Ottoman_Arm_2'
obj.rotation_euler = (0.0, 0.0, 2.513274)
obj.scale = (0.4, 0.05, 0.05)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.038197, 2.082443, 0.04))
obj = bpy.context.active_object
obj.name = 'Ottoman_Arm_3'
obj.rotation_euler = (0.0, 0.0, 3.769911)
obj.scale = (0.4, 0.05, 0.05)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.261803, 2.009789, 0.04))
obj = bpy.context.active_object
obj.name = 'Ottoman_Arm_4'
obj.rotation_euler = (0.0, 0.0, 5.026548)
obj.scale = (0.4, 0.05, 0.05)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.04, depth=0.12, location=(1.2, 2.2, 0.06))
obj = bpy.context.active_object
obj.name = 'Ottoman_Base_Post'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.020'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.2, 2.2, 0.28))
obj = bpy.context.active_object
obj.name = 'Ottoman_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.52, 0.32)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['Brown_Fabric'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.18, depth=0.06, location=(3.0, 4.2, 0.06))
obj = bpy.context.active_object
obj.name = 'Red_Stool_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.013'
obj.data.materials.append(bpy.data.materials['Red_Orange'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.09, depth=0.18, location=(3.0, 4.2, 0.24))
obj = bpy.context.active_object
obj.name = 'Red_Stool_Mid'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.012'
obj.data.materials.append(bpy.data.materials['Red_Orange'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.18, depth=0.08, location=(3.0, 4.2, 0.42))
obj = bpy.context.active_object
obj.name = 'Red_Stool_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.011'
obj.data.materials.append(bpy.data.materials['Red_Orange'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.16, depth=0.04, location=(4.2, 3.6, 0.04))
obj = bpy.context.active_object
obj.name = 'Side_Table_1_Base'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.010'
obj.data.materials.append(bpy.data.materials['Dark_Top'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.03, depth=0.56, location=(4.2, 3.6, 0.36))
obj = bpy.context.active_object
obj.name = 'Side_Table_1_Post'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.009'
obj.data.materials.append(bpy.data.materials['Silver_Metal'])

bpy.ops.mesh.primitive_cylinder_add(vertices=32, radius=0.24, depth=0.04, location=(4.2, 3.6, 0.66))
obj = bpy.context.active_object
obj.name = 'Side_Table_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.name = 'Cylinder.008'
obj.data.materials.append(bpy.data.materials['Dark_Top'])

bpy.ops.object.light_add(type='SUN', location=(0.0, 0.0, 10.0))
obj = bpy.context.active_object
obj.name = 'Sun_Main'
obj.rotation_euler = (0.610865, 0.0, 0.698132)
obj.data.energy = 2.5
obj.data.color = (1.0, 0.97, 0.94)

bpy.ops.mesh.primitive_cube_add(size=1, location=(-5.2, 3.5, 0.32))
obj = bpy.context.active_object
obj.name = 'TV_Stand_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 0.72, 0.64)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['White_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-5.2, 3.16, 0.85))
obj = bpy.context.active_object
obj.name = 'TV_Stand_Screen'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.0, 0.08, 0.44)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['TV_Screen'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-5.2, 3.5, 0.66))
obj = bpy.context.active_object
obj.name = 'TV_Stand_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.2, 0.72, 0.04)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['White_Cabinet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 6.05, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.1, 3.0)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -6.05, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (14.0, 0.1, 3.0)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-7.05, 0.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 12.0, 3.0)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(5.5, 6.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Orange_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.0, 0.1, 3.0)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Orange_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(7.0, 4.2, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Orange_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 3.6, 3.0)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Orange_Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(7.05, 0.0, 1.5))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 12.0, 3.0)
obj.data.name = 'Cube.005'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.5, 0.05))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_CrossBar'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.28, 0.05, 0.05)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.64, 0.5, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_Foot_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.64, 0.5, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_Foot_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.64, 0.5, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_Post_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.64, 0.5, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_Post_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.5, 0.76))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_1_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.5, 0.8, 0.06)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['White_Top'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.2, -0.8, 0.05))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_CrossBar'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.28, 0.05, 0.05)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.84, -0.8, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_Foot_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.56, -0.8, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_Foot_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.84, -0.8, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_Post_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-2.56, -0.8, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_Post_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-3.2, -0.8, 0.76))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_2_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.5, 0.8, 0.06)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['White_Top'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, -2.2, 0.05))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_CrossBar'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.28, 0.05, 0.05)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.16, -2.2, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_Foot_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.44, -2.2, 0.035))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_Foot_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.64, 0.07)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.16, -2.2, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_Post_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(2.44, -2.2, 0.4))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_Post_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.07, 0.07, 0.8)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Table_Base'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.8, -2.2, 0.76))
obj = bpy.context.active_object
obj.name = 'Workspace_Table_3_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.5, 0.8, 0.06)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['White_Top'])

