"""
Blender Scene: scene0222_00.blend
Objects: 193
Materials: 16
Generated by Export BPY Code addon v1.2.1
"""

import bpy
import math

# ============================================================
# Clear Scene
# ============================================================
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
for m in list(bpy.data.materials): bpy.data.materials.remove(m)
for m in list(bpy.data.meshes): bpy.data.meshes.remove(m)
for m in list(bpy.data.lights): bpy.data.lights.remove(m)
for m in list(bpy.data.cameras): bpy.data.cameras.remove(m)

# ============================================================
# Render Settings
# ============================================================
bpy.context.scene.render.engine = 'BLENDER_EEVEE'
bpy.context.scene.render.resolution_x = 1920
bpy.context.scene.render.resolution_y = 1080
bpy.context.scene.render.resolution_percentage = 100
bpy.context.scene.eevee.taa_render_samples = 64

# World Environment
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new('World')
    bpy.context.scene.world = world
world.use_nodes = True
_bg = world.node_tree.nodes.get('Background')
if _bg:
    _bg.inputs['Color'].default_value = (0.8, 0.82, 0.86, 1.0)
    _bg.inputs['Strength'].default_value = 0.4

# ============================================================
# Materials
# ============================================================
mat_Baseboard = bpy.data.materials.new(name='Baseboard')
mat_Baseboard.use_nodes = True
_bsdf = mat_Baseboard.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.92, 0.92, 0.9, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Blind = bpy.data.materials.new(name='Blind')
mat_Blind.use_nodes = True
_bsdf = mat_Blind.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.22, 0.22, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.75
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Blue_Bin = bpy.data.materials.new(name='Blue_Bin')
mat_Blue_Bin.use_nodes = True
_bsdf = mat_Blue_Bin.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.12, 0.25, 0.72, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.5
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Book_Blue = bpy.data.materials.new(name='Book_Blue')
mat_Book_Blue.use_nodes = True
_bsdf = mat_Book_Blue.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.18, 0.28, 0.68, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Book_White = bpy.data.materials.new(name='Book_White')
mat_Book_White.use_nodes = True
_bsdf = mat_Book_White.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.88, 0.87, 0.84, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.75
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Ceiling = bpy.data.materials.new(name='Ceiling')
mat_Ceiling.use_nodes = True
_bsdf = mat_Ceiling.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.95, 0.95, 0.93, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.12
mat_Ceiling.blend_method = 'BLEND'

mat_Cushion = bpy.data.materials.new(name='Cushion')
mat_Cushion.use_nodes = True
_bsdf = mat_Cushion.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.2, 0.22, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.88
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Dark_Wood = bpy.data.materials.new(name='Dark_Wood')
mat_Dark_Wood.use_nodes = True
_bsdf = mat_Dark_Wood.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.22, 0.14, 0.06, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.7
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Floor_Carpet = bpy.data.materials.new(name='Floor_Carpet')
mat_Floor_Carpet.use_nodes = True
_bsdf = mat_Floor_Carpet.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.08, 0.12, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.97
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Lamp_Black = bpy.data.materials.new(name='Lamp_Black')
mat_Lamp_Black.use_nodes = True
_bsdf = mat_Lamp_Black.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.05, 0.05, 0.05, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.3
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Mattress = bpy.data.materials.new(name='Mattress')
mat_Mattress.use_nodes = True
_bsdf = mat_Mattress.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.1, 0.12, 0.2, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.9
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Teal_Bin = bpy.data.materials.new(name='Teal_Bin')
mat_Teal_Bin.use_nodes = True
_bsdf = mat_Teal_Bin.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.12, 0.62, 0.68, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.45
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Wall = bpy.data.materials.new(name='Wall')
mat_Wall.use_nodes = True
_bsdf = mat_Wall.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.9, 0.88, 0.82, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.8
_bsdf.inputs['Metallic'].default_value = 0.0

mat_Win_Frame = bpy.data.materials.new(name='Win_Frame')
mat_Win_Frame.use_nodes = True
_bsdf = mat_Win_Frame.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.42, 0.42, 0.4, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.4
_bsdf.inputs['Metallic'].default_value = 0.3

mat_Win_Glass = bpy.data.materials.new(name='Win_Glass')
mat_Win_Glass.use_nodes = True
_bsdf = mat_Win_Glass.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.7, 0.82, 0.95, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.05
_bsdf.inputs['Metallic'].default_value = 0.0
_bsdf.inputs['Alpha'].default_value = 0.2
mat_Win_Glass.blend_method = 'BLEND'

mat_Wood = bpy.data.materials.new(name='Wood')
mat_Wood.use_nodes = True
_bsdf = mat_Wood.node_tree.nodes['Principled BSDF']
_bsdf.inputs['Base Color'].default_value = (0.6, 0.35, 0.14, 1.0)
_bsdf.inputs['Roughness'].default_value = 0.65
_bsdf.inputs['Metallic'].default_value = 0.0

# ============================================================
# Objects
# ============================================================
bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 2.19, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.8, 0.12, 0.12)
obj.data.name = 'Cube.006'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -2.19, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.8, 0.12, 0.12)
obj.data.name = 'Cube.007'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.84, 0.0, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 4.5, 0.12)
obj.data.name = 'Cube.008'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.0, 0.06))
obj = bpy.context.active_object
obj.name = 'Baseboard_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 4.5, 0.12)
obj.data.name = 'Cube.009'
obj.data.materials.append(bpy.data.materials['Baseboard'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 0.39, 0.605))
obj = bpy.context.active_object
obj.name = 'Bed_Footboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.96, 0.08, 1.21)
obj.data.name = 'Cube.135'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 2.21, 0.605))
obj = bpy.context.active_object
obj.name = 'Bed_Headboard'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.96, 0.08, 1.21)
obj.data.name = 'Cube.134'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.52, 2.19, 0.55))
obj = bpy.context.active_object
obj.name = 'Bed_Leg_0p42_0p89'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.1, 1.1)
obj.data.name = 'Cube.133'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.52, 0.41, 0.55))
obj = bpy.context.active_object
obj.name = 'Bed_Leg_0p42_n0p89'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.1, 1.1)
obj.data.name = 'Cube.132'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.68, 2.19, 0.55))
obj = bpy.context.active_object
obj.name = 'Bed_Leg_n0p42_0p89'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.1, 1.1)
obj.data.name = 'Cube.131'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.68, 0.41, 0.55))
obj = bpy.context.active_object
obj.name = 'Bed_Leg_n0p42_n0p89'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 0.1, 1.1)
obj.data.name = 'Cube.130'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 1.3, 1.22))
obj = bpy.context.active_object
obj.name = 'Bed_Mattress'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.88, 1.8, 0.24)
obj.data.name = 'Cube.142'
obj.data.materials.append(bpy.data.materials['Mattress'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 1.3, 1.1))
obj = bpy.context.active_object
obj.name = 'Bed_Platform'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.94, 1.88, 0.06)
obj.data.name = 'Cube.141'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.67, 1.3, 1.24))
obj = bpy.context.active_object
obj.name = 'Bed_Rail_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.74, 0.05)
obj.data.name = 'Cube.139'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.53, 1.3, 1.24))
obj = bpy.context.active_object
obj.name = 'Bed_Rail_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.1, 1.74, 0.05)
obj.data.name = 'Cube.140'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 0.39, 0.28))
obj = bpy.context.active_object
obj.name = 'Bed_Rung_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.05, 0.048)
obj.data.name = 'Cube.136'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 0.39, 0.58))
obj = bpy.context.active_object
obj.name = 'Bed_Rung_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.05, 0.048)
obj.data.name = 'Cube.137'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.1, 0.39, 0.88))
obj = bpy.context.active_object
obj.name = 'Bed_Rung_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.92, 0.05, 0.048)
obj.data.name = 'Cube.138'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.95, 1.37, 0.22))
obj = bpy.context.active_object
obj.name = 'Blue_Bin_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.36, 0.28, 0.44)
obj.data.name = 'Cube.188'
obj.data.materials.append(bpy.data.materials['Blue_Bin'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.95, 1.37, 0.44))
obj = bpy.context.active_object
obj.name = 'Blue_Bin_Rim'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.36, 0.28, 0.03)
obj.data.name = 'Cube.189'
obj.data.materials.append(bpy.data.materials['Blue_Bin'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.41, 1.86, 0.805))
obj = bpy.context.active_object
obj.name = 'Book_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.15, 0.03)
obj.data.name = 'Cube.183'
obj.data.materials.append(bpy.data.materials['Book_Blue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.41, 1.86, 0.834))
obj = bpy.context.active_object
obj.name = 'Book_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.15, 0.028)
obj.data.name = 'Cube.184'
obj.data.materials.append(bpy.data.materials['Book_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.41, 1.86, 0.864))
obj = bpy.context.active_object
obj.name = 'Book_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.15, 0.032)
obj.data.name = 'Cube.185'
obj.data.materials.append(bpy.data.materials['Book_Blue'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.41, 1.86, 0.893))
obj = bpy.context.active_object
obj.name = 'Book_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.15, 0.026)
obj.data.name = 'Cube.186'
obj.data.materials.append(bpy.data.materials['Book_White'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.41, 1.86, 0.9235))
obj = bpy.context.active_object
obj.name = 'Book_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.15, 0.035)
obj.data.name = 'Cube.187'
obj.data.materials.append(bpy.data.materials['Book_Blue'])

bpy.ops.object.camera_add(location=(-0.3, -1.9, 1.5))
obj = bpy.context.active_object
obj.name = 'Camera_Main'
obj.rotation_euler = (1.32645, 0.0, 0.087266)
obj.data.lens = 20.0
obj.data.clip_start = 0.1
obj.data.clip_end = 1000.0

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.52, 1.09, 0.64))
obj = bpy.context.active_object
obj.name = 'Chair_Arm_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.36, 0.05)
obj.data.name = 'Cube.165'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.52, 0.95, 0.55))
obj = bpy.context.active_object
obj.name = 'Chair_Arm_Post_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.18)
obj.data.name = 'Cube.166'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.08, 0.95, 0.55))
obj = bpy.context.active_object
obj.name = 'Chair_Arm_Post_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.05, 0.18)
obj.data.name = 'Cube.168'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.08, 1.09, 0.64))
obj = bpy.context.active_object
obj.name = 'Chair_Arm_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.05, 0.36, 0.05)
obj.data.name = 'Cube.167'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 1.3, 0.68))
obj = bpy.context.active_object
obj.name = 'Chair_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.06, 0.44)
obj.data.name = 'Cube.162'
obj.data.materials.append(bpy.data.materials['Cushion'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 1.31, 0.68))
obj = bpy.context.active_object
obj.name = 'Chair_Back_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.05, 0.46)
obj.data.name = 'Cube.163'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.48, 0.91, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_Leg_n0_n0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.46)
obj.data.name = 'Cube.169'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.48, 1.27, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_Leg_n0_p0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.46)
obj.data.name = 'Cube.170'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.12, 0.91, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_Leg_p0_n0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.46)
obj.data.name = 'Cube.171'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.12, 1.27, 0.23))
obj = bpy.context.active_object
obj.name = 'Chair_Leg_p0_p0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.06, 0.06, 0.46)
obj.data.name = 'Cube.172'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 1.09, 0.46))
obj = bpy.context.active_object
obj.name = 'Chair_Seat'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.44, 0.08)
obj.data.name = 'Cube.160'
obj.data.materials.append(bpy.data.materials['Cushion'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 1.09, 0.42))
obj = bpy.context.active_object
obj.name = 'Chair_Seat_Frame'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.46, 0.06)
obj.data.name = 'Cube.161'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.3, 1.31, 0.9))
obj = bpy.context.active_object
obj.name = 'Chair_Top_Rail'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.46, 0.06, 0.05)
obj.data.name = 'Cube.164'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 2.22, 0.38))
obj = bpy.context.active_object
obj.name = 'Desk_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.36, 0.02, 0.76)
obj.data.name = 'Cube.149'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.11, 1.585, 0.14))
obj = bpy.context.active_object
obj.name = 'Desk_Drawer_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.03, 0.2)
obj.data.name = 'Cube.146'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.11, 1.585, 0.38))
obj = bpy.context.active_object
obj.name = 'Desk_Drawer_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.03, 0.2)
obj.data.name = 'Cube.147'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.11, 1.585, 0.62))
obj = bpy.context.active_object
obj.name = 'Desk_Drawer_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.03, 0.2)
obj.data.name = 'Cube.148'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.11, 1.91, 0.38))
obj = bpy.context.active_object
obj.name = 'Desk_Drawer_Column'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.24, 0.64, 0.76)
obj.data.name = 'Cube.145'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.09, 1.91, 0.38))
obj = bpy.context.active_object
obj.name = 'Desk_Panel_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.64, 0.76)
obj.data.name = 'Cube.144'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 1.91, 0.76))
obj = bpy.context.active_object
obj.name = 'Desk_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.36, 0.64, 0.06)
obj.data.name = 'Cube.143'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.6, 0.6, 0.41))
obj = bpy.context.active_object
obj.name = 'Dresser_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.56, 0.48, 0.82)
obj.data.name = 'Cube.173'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.6, 0.355, 0.1))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.03, 0.17)
obj.data.name = 'Cube.174'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.6, 0.355, 0.3))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.03, 0.17)
obj.data.name = 'Cube.175'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.6, 0.355, 0.5))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.03, 0.17)
obj.data.name = 'Cube.176'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.6, 0.355, 0.7))
obj = bpy.context.active_object
obj.name = 'Dresser_Drawer_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.52, 0.03, 0.17)
obj.data.name = 'Cube.177'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 0.0, -0.05))
obj = bpy.context.active_object
obj.name = 'Floor'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.8, 4.5, 0.1)
obj.data.name = 'Cube'
obj.data.materials.append(bpy.data.materials['Floor_Carpet'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 2.22, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.02, 0.52)
obj.data.name = 'Cube.153'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 2.06, 0.79))
obj = bpy.context.active_object
obj.name = 'Hutch_Bottom'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.34, 0.04)
obj.data.name = 'Cube.151'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.688, 2.06, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Divider_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.34, 0.52)
obj.data.name = 'Cube.156'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.212, 2.06, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Divider_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.34, 0.52)
obj.data.name = 'Cube.157'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 2.06, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Mid_Shelf'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.34, 0.03)
obj.data.name = 'Cube.152'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.15, 2.06, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Side_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.34, 0.52)
obj.data.name = 'Cube.154'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.25, 2.06, 1.05))
obj = bpy.context.active_object
obj.name = 'Hutch_Side_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.04, 0.34, 0.52)
obj.data.name = 'Cube.155'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.45, 2.06, 1.31))
obj = bpy.context.active_object
obj.name = 'Hutch_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (1.4, 0.34, 0.04)
obj.data.name = 'Cube.150'
obj.data.materials.append(bpy.data.materials['Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.03, 2.06, 1.45))
obj = bpy.context.active_object
obj.name = 'Lamp_Arm'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.03, 0.28)
obj.data.name = 'Cube.158'
obj.data.materials.append(bpy.data.materials['Lamp_Black'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.03, 2.06, 1.63))
obj = bpy.context.active_object
obj.name = 'Lamp_Shade'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.12, 0.08)
obj.data.name = 'Cube.159'
obj.data.materials.append(bpy.data.materials['Lamp_Black'])

bpy.ops.object.light_add(type='AREA', location=(-0.6, -1.6, 2.4))
obj = bpy.context.active_object
obj.name = 'Light_Area_Fill'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 200.0
obj.data.size = 2.0

bpy.ops.object.light_add(type='AREA', location=(0.0, 0.0, 2.48))
obj = bpy.context.active_object
obj.name = 'Light_Area_Main'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.data.energy = 450.0
obj.data.size = 3.0

bpy.ops.object.light_add(type='AREA', location=(1.65, -0.2, 1.7))
obj = bpy.context.active_object
obj.name = 'Light_Window'
obj.rotation_euler = (0.0, 1.570796, 0.0)
obj.data.energy = 350.0
obj.data.size = 1.4

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.75, 1.86, 0.93))
obj = bpy.context.active_object
obj.name = 'Teal_Bin_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.28, 0.2, 0.28)
obj.data.name = 'Cube.181'
obj.data.materials.append(bpy.data.materials['Teal_Bin'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-0.75, 1.86, 1.07))
obj = bpy.context.active_object
obj.name = 'Teal_Bin_Rim'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.28, 0.2, 0.03)
obj.data.name = 'Cube.182'
obj.data.materials.append(bpy.data.materials['Teal_Bin'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, 2.19, 1.3))
obj = bpy.context.active_object
obj.name = 'Wall_Back'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.8, 0.12, 2.6)
obj.data.name = 'Cube.001'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(0.0, -2.19, 1.3))
obj = bpy.context.active_object
obj.name = 'Wall_Front'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (3.8, 0.12, 2.6)
obj.data.name = 'Cube.002'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.84, 0.0, 1.3))
obj = bpy.context.active_object
obj.name = 'Wall_Left'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 4.5, 2.6)
obj.data.name = 'Cube.003'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.0, 1.3))
obj = bpy.context.active_object
obj.name = 'Wall_Right'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.12, 4.5, 2.6)
obj.data.name = 'Cube.004'
obj.data.materials.append(bpy.data.materials['Wall'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.66, 2.01, 0.8))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Body'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.44, 0.44, 1.6)
obj.data.name = 'Cube.178'
obj.data.materials.append(bpy.data.materials['Dark_Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.76, 1.778, 0.8))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Door_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.024, 1.58)
obj.data.name = 'Cube.179'
obj.data.materials.append(bpy.data.materials['Dark_Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(-1.56, 1.778, 0.8))
obj = bpy.context.active_object
obj.name = 'Wardrobe_Door_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.2, 0.024, 1.58)
obj.data.name = 'Cube.180'
obj.data.materials.append(bpy.data.materials['Dark_Wood'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -1.4, 0.82))
obj = bpy.context.active_object
obj.name = 'Win_1_Frame_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.012'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -1.81, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_1_Frame_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.013'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.99, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_1_Frame_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.014'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -1.4, 2.28))
obj = bpy.context.active_object
obj.name = 'Win_1_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.011'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -1.4, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_1_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.76, 1.4)
obj.data.name = 'Cube.010'
obj.data.materials.append(bpy.data.materials['Win_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 0.872))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.015'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 0.927))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.016'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.422))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.025'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.477))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_11'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.026'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.532))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_12'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.027'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.587))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_13'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.028'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.642))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_14'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.029'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.697))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.030'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.752))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_16'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.031'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.807))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_17'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.032'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.862))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.033'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.917))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_19'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.034'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 0.982))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.017'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.972))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_20'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.035'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 2.027))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_21'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.036'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 2.082))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_22'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.037'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 2.137))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_23'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.038'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 2.192))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_24'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.039'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.037))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.018'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.092))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.019'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.147))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.020'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.202))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.021'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.257))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.022'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.312))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.023'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -1.4, 1.367))
obj = bpy.context.active_object
obj.name = 'Win_1_Slat_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.024'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.65, 0.82))
obj = bpy.context.active_object
obj.name = 'Win_2_Frame_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.042'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -1.06, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_2_Frame_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.043'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.24, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_2_Frame_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.044'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.65, 2.28))
obj = bpy.context.active_object
obj.name = 'Win_2_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.041'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.65, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_2_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.76, 1.4)
obj.data.name = 'Cube.040'
obj.data.materials.append(bpy.data.materials['Win_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 0.872))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.045'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 0.927))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.046'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.422))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.055'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.477))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_11'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.056'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.532))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_12'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.057'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.587))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_13'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.058'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.642))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_14'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.059'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.697))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.060'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.752))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_16'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.061'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.807))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_17'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.062'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.862))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.063'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.917))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_19'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.064'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 0.982))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.047'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.972))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_20'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.065'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 2.027))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_21'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.066'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 2.082))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_22'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.067'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 2.137))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_23'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.068'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 2.192))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_24'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.069'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.037))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.048'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.092))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.049'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.147))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.050'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.202))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.051'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.257))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.052'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.312))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.053'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, -0.65, 1.367))
obj = bpy.context.active_object
obj.name = 'Win_2_Slat_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.054'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.1, 0.82))
obj = bpy.context.active_object
obj.name = 'Win_3_Frame_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.072'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, -0.31, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_3_Frame_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.073'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.51, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_3_Frame_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.074'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.1, 2.28))
obj = bpy.context.active_object
obj.name = 'Win_3_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.071'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.1, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_3_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.76, 1.4)
obj.data.name = 'Cube.070'
obj.data.materials.append(bpy.data.materials['Win_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 0.872))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.075'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 0.927))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.076'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.422))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.085'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.477))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_11'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.086'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.532))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_12'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.087'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.587))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_13'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.088'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.642))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_14'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.089'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.697))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.090'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.752))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_16'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.091'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.807))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_17'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.092'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.862))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.093'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.917))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_19'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.094'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 0.982))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.077'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.972))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_20'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.095'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 2.027))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_21'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.096'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 2.082))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_22'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.097'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 2.137))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_23'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.098'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 2.192))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_24'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.099'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.037))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.078'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.092))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.079'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.147))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.080'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.202))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.081'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.257))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.082'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.312))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.083'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.1, 1.367))
obj = bpy.context.active_object
obj.name = 'Win_3_Slat_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.084'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.85, 0.82))
obj = bpy.context.active_object
obj.name = 'Win_4_Frame_Bot'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.102'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.44, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_4_Frame_L'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.103'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 1.26, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_4_Frame_R'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.06, 1.4)
obj.data.name = 'Cube.104'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.85, 2.28))
obj = bpy.context.active_object
obj.name = 'Win_4_Frame_Top'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.08, 0.82, 0.06)
obj.data.name = 'Cube.101'
obj.data.materials.append(bpy.data.materials['Win_Frame'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.84, 0.85, 1.55))
obj = bpy.context.active_object
obj.name = 'Win_4_Glass'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.03, 0.76, 1.4)
obj.data.name = 'Cube.100'
obj.data.materials.append(bpy.data.materials['Win_Glass'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 0.872))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_0'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.105'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 0.927))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_1'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.106'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.422))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_10'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.115'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.477))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_11'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.116'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.532))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_12'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.117'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.587))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_13'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.118'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.642))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_14'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.119'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.697))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_15'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.120'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.752))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_16'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.121'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.807))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_17'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.122'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.862))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_18'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.123'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.917))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_19'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.124'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 0.982))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_2'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.107'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.972))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_20'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.125'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 2.027))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_21'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.126'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 2.082))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_22'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.127'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 2.137))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_23'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.128'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 2.192))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_24'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.129'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.037))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_3'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.108'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.092))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_4'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.109'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.147))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_5'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.110'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.202))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_6'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.111'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.257))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_7'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.112'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.312))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_8'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.113'
obj.data.materials.append(bpy.data.materials['Blind'])

bpy.ops.mesh.primitive_cube_add(size=1, location=(1.83, 0.85, 1.367))
obj = bpy.context.active_object
obj.name = 'Win_4_Slat_9'
obj.rotation_euler = (0.0, 0.0, 0.0)
obj.scale = (0.016, 0.74, 0.044)
obj.data.name = 'Cube.114'
obj.data.materials.append(bpy.data.materials['Blind'])

